### ISSUE TITLE
Rotate LSBC revocation registries

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#102]
Once the agent upgrade is completed, rotate the revocation registry for the credential being issued by using the `/revocation/active-registry/{cred_def_id}/rotate` endpoint.

- [x] Dev
- [x] Test
- [x] Prod

Related, Askar, upgrade issue; https://github.com/bcgov/DITP-DevOps/issues/83
- Details tracked there.

**Comment by WadeBarnes** [comment]
LSBC revocation registries have been rotated in all environments.
