### ISSUE TITLE
Rotate IDIM revocation registries

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#103]
Once the agent upgrade is completed, rotate the revocation registry for the credential being issued by using the `/revocation/active-registry/{cred_def_id}/rotate` endpoint.

**Comment by marcos-carretero** [comment]
cred_def_id for each IDIM environment
- [ ] **DEV:** XpgeQa93eZvGSZBZef3PHn:3:CL:28075:PersonDEV
- [ ] **SIT:** 7xjfawcnyTUcduWVysLww5:3:CL:28075:PersonSIT
- [ ] **QA:** KCxVC8GkKywjhWJnUfCmkW:3:CL:20:PersonQA
- [ ] **PROD:** RGjWbW1eycP7FrMf4QJvX8:3:CL:13:Person

**Comment by WadeBarnes** [comment]
Tracking the rotation responses here; https://github.com/bcgov/DITP-DevOps/issues/109

**Comment by WadeBarnes** [comment]
This is complete
