### ISSUE TITLE
Protect creating Traction reservations using IDIR in dev/test/prod

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#112]
To limit the number of requests, and WHO can request a tenant in our `dev`/`test`/`prod` instances, we should enable IDIR authentication to gate access to creating a new reservation.

**Comment by esune** [comment]
This needs incorporating into `test` and `prod`. See [this](https://github.com/bcgov/traction/blob/de95c6892818c5d86abb59f0ac0ebfda19aa0c3e/deploy/traction/values-development.yaml#L50-L53) for reference.

**Comment by loneil** [comment]
Note to flag the Tenant UI to enforce OIDC login on reservation use this flag, set to true
```
  ## @param ui.oidc.showOIDCReservationLogin OIDC reservation login
  showOIDCReservationLogin: false
```

**Comment by esune** [comment]
Will be completed with #133
