### ISSUE TITLE
Deploy instances of the Aries Mediator Service with persistent queue support

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#113]
When testing, please use the following instances.  The `-pq` instances are being scaled down and decommissioned as the following instances are migrated over to use the persistent queue.
- `dev`: https://aries-mediator-agent-dev.apps.silver.devops.gov.bc.ca
- `test`: https://aries-mediator-agent-test.apps.silver.devops.gov.bc.ca
- `prod`: https://aries-mediator-agent-pq.vonx.io

`-pq` instances - Being scaled down and decommissioned as the above instances are migrated over to use the persistent queue.
- [x] `dev` - **Decommissioned**
  - https://aries-mediator-agent-pq-dev.apps.silver.devops.gov.bc.ca
- [x] `test`  - **Decommissioned**
  - https://aries-mediator-agent-pq-test.apps.silver.devops.gov.bc.ca
- [x] `prod`  - **Decommissioned**
  - https://aries-mediator-agent-pq.vonx.io

Current State:
- Complete
- ~Preliminary instances have been deployed to `dev` and `test` based on the work here; https://github.com/hyperledger/aries-mediator-service/pull/78.~
- ~The persistent queue profile(s) were added here; https://github.com/bcgov/openshift-aries-mediator-service/commit/c341bca0b1f14aa07958f5760b8ca14dce08bb90~

Next Steps:
- [x] Review and merge PR
- [x] Update `-pq` instance configuration to point at the official source repos.
- [x] Update the `-pq` instance deployments.
  - [x] `dev`
  - [x] `test`
- [x] Complete `-pq` instance testing with help from the Wallet team.
  - [x] `dev` - In progress
  - [x] `test`
- [x] Deploy to `-pq` instance to `prod` and smoke test.
- [x] Migrate existing instances over to use a persistent queue - So we can reuse the existing invitations and URLs.
  - [x] `dev`
    - https://aries-mediator-agent-dev.apps.silver.devops.gov.bc.ca/
  - [x] `test`
    - https://aries-mediator-agent-test.apps.silver.devops.gov.bc.ca/
  - [x] `prod`
    - https://aries-mediator-agent.vonx.io/
- [x] Decommission the `-pq` mediator instances and resources.
  - [x] `tools`
    - Resources
  - [x] `dev` - **Decommissioned**
    - https://aries-mediator-agent-pq-dev.apps.silver.devops.gov.bc.ca
  - [x] `test` - **Decommissioned**
    - https://aries-mediator-agent-pq-test.apps.silver.devops.gov.bc.ca
  - [x] `prod` - **Decommissioned**
    - https://aries-mediator-agent-pq.vonx.io
- [ ] Final testing of `prod` environment

**Comment by jleach** [comment]
A few of us have been testing this for weeks now with no issues. I think its safe to carry on promoting this to prod.

**Comment by WadeBarnes** [comment]
We're at a point were we want to migrate from the existing (non-persistent) mediator instances to the new instances backed by the persistent queue.  I'd like to migrate the URLs to the new instances, but that will require some co-ordination; different instance equals different invite.

@cvarjao, @jleach, Looking for how you'd like to proceed.

**Comment by cvarjao** [comment]
is there a way to do it preserving existing invitation? I am not sure how we are going to coordinate releasing a new version of the wallet with the new invitation and the mediator server-side changes. We can change the invitation later, but I am not sure what would happen if people already using that invitation/mediation.

**Comment by WadeBarnes** [comment]
> is there a way to do it preserving existing invitation? I am not sure how we are going to coordinate releasing a new version of the wallet with the new invitation and the mediator server-side changes. We can change the invitation later, but I am not sure what would happen if people already using that invitation/mediation.

I'll investigate.

**Comment by WadeBarnes** [comment]
I've migrated the existing `dev` mediator over to a persistent queue setup and smoke tested it using the load test tool and an old invite I had.  Would someone from the wallet team be able to run some tests in `dev` and make sure any old invites you have still work, and that the mediator is working as expected.  Then we can migrate `test` and confirm before moving on to schedule `prod`.

cc @cvarjao, @jleach

**Comment by jleach** [comment]
I think if we choose to change the prod mediator invitation we would need to run both in parallel while users update the app. We may also want to add some logic that deletes old mediator connections. It typically does not show up in the contact list unless developer options are enabled so not feasible for users to do.

**Comment by WadeBarnes** [comment]
> I think if we choose to change the prod mediator invitation we would need to run both in parallel while users update the app. We may also want to add some logic that deletes old mediator connections. It typically does not show up in the contact list unless developer options are enabled so not feasible for users to do.

This is no longer an issue with the migration approach I'm taking now.  I'm migrating the existing instances over to use the persistent queue, so all of the existing connections and invites will continue to work.  The URLs will not change either.

**Comment by WadeBarnes** [comment]
> We may also want to add some logic that deletes old mediator connections.

This brings up some thoughts about cleaning up connections on the mediator side.
  - Once the Wallet makes a connection to the mediator, it reuses it; correct?
  - If the connection was deleted from the mediator side, what would happen?  How would the Wallet behave/respond?

**Comment by WadeBarnes** [comment]
I was able to perform enough testing in `dev` to have enough confidence to migrate the mediator instance in `test`.  I've smoke tested `test` with a couple old invites to ensure they continued to work.

**Comment by WadeBarnes** [comment]
The `test` environment is getting tested along with the Firebase updates; https://github.com/bcgov/DITP-DevOps/issues/106

**Comment by WadeBarnes** [comment]
Blocked by progress on https://github.com/bcgov/DITP-DevOps/issues/106.

**Comment by WadeBarnes** [comment]
Please reassign to me when this is ready to move forward.

**Comment by WadeBarnes** [comment]
The `prod` mediator instance has been upgraded and migrated to use the persistent queue.  Updates include the Firebase plugin; https://github.com/bcgov/DITP-DevOps/issues/106

cc @bryce-mcmath, @jamshale, @cvarjao, @jleach

**Comment by WadeBarnes** [comment]
Assigned to @bryce-mcmath for final testing, as this will be tested along with the Firebase plugin updates.  Please close when testing is successfully completed.

**Comment by esune** [comment]
> [@bryce-mcmath](https://github.com/bryce-mcmath), How has the testing been going?

@bryce-mcmath any updates on this? Can we close the issue or are there still pending tasks?

**Comment by bryce-mcmath** [comment]
@esune ah sorry, I didn't realize there were two mediator deployment tickets. I commented here: https://github.com/bcgov/DITP-DevOps/issues/106#issuecomment-1959919742

All Testflight testing has gone well and we are about to do a release that includes GA push notifications
