### ISSUE TITLE
Upgrade sandbox Traction to latest chart release

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#115]
The sandbox release is currently running Traction `0.2.14`, which has separate charts for `traction` and `tenant-ui`.
The latest releases consolidate components, and make the `tenant-ui` an option that can be enabled from the main chart.

Acceptance Criteria:
- [ ] Update the values file used for deployment to account for the new changes
- [x] Use the hosted helm chart repository in GitHub to deploy the chart, instead of the local fork
- [ ] PR the updated configuration to https://github.com/bcgov/trust-over-ip-configurations

**Comment by esune** [comment]
#116 is already using the hosted chart in the Traction repo, this issue is to assess whether the values file needs to be updated, and implement the required changes. Additionally, the `tenant-ui` values file is now not necessary anymore, so it will need to be removed.

**Comment by loneil** [comment]
I have created a pull request in the repo with the values changing the sandbox to use the single ledger as discussed.
https://github.com/bcgov/trust-over-ip-configurations/pull/149

Once that is reviewed and applied we could redeploy I believe to have it take affect.

cc @esune / @rajpalc7

**Comment by rajpalc7** [comment]
@esune - Assuming Once this is reviewed and applied, Ivan will have to release a new chart version and then I will be able to deploy the traction-sandbox again.

**Comment by loneil** [comment]
I'm not sure how it works but can you run the same chart version against a values file to update things? Or does a Helm release need to happen with each update to the values files?

**Comment by esune** [comment]
@rajpalc7 the PR was approved and merged. You should be able to validate the configurations against the current latest published release of the Traction chart - `0.2.5`. The change @loneil submitted a PR for does not require a new chart to be published, as it is just configuration.

**Comment by rajpalc7** [comment]
I was able to validate and deploy the latest version now.

**Comment by esune** [comment]
Thanks @rajpalc7, closing as done.
