### ISSUE TITLE
Traction sandbox reset/redeploy automation

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#116]
We want the traction sandbox instance to be reset and re-deployed, using the latest published chart, periodically.

The suggested approach is to implement a Github Action (to be stored in https://github.com/bcgov/trust-over-ip-configurations) that will install/uninstall/re-install the sandbox on a schedule.

We have Github actions completing similar work (with different triggers) in the Traction repo (see https://github.com/bcgov/traction/blob/main/.github/workflows/on_pr_closed.yaml and https://github.com/bcgov/traction/blob/main/.github/workflows/on_pr_opened.yaml as examples).

Acceptance Criteria:
- [x] A Github action is created. The action will uninstall the helm chart and any leftover deployment artifacts, and re-install it periodically.
- [x] The trigger should be set to run every two weeks, on the night between Sunday and Monday at 2am PST

**Comment by esune** [comment]
@rajpalc7 checking-in about this. A n updated chart was released so you should be able to proceed and wrap this up as well as #115.

**Comment by rajpalc7** [comment]
Hi @esune, I was able to make github actions work to uninstall and install the release now. The new release is working fine now. I am going to close this ticket  in favour of #123
