### ISSUE TITLE
TEST Env - Traction environment Endorser re-connections

### ISSUE THREAD

**Issue by loneil** [bcgov/DITP-DevOps#119]
Tracking same operational steps for existing Tenants as described for Dev here https://github.com/bcgov/DITP/issues/69

Should ensure existing tenants are made aware of changes needed to coincide with when the current codebase goes to TEST.

**Comment by esune** [comment]
The [public DID for the BCovrin test](https://github.com/bcgov/traction/blob/7c5b41fbc8b70535af358756c0d9c633fdbb3a17/charts/traction/values.yaml#L144C45-L144C45) endorser should be switched to `4pgFAjnSVKCr7CMfpqDjhu`.

**Comment by loneil** [comment]
This will need coordination with the deployment time of the next release to the test env, and possible messaging about possible minor outages of issuance.
