### ISSUE TITLE
Upgrades to sandbox refresh action

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#123]
The GHA used to refresh our Traction Sandbox deployment is currently made up of two separate actions, running on two cron schedules. The issue with this is that, in the event the first one doesn't complete, the second one would still start and potentially cause issues.

The objective is to create one GHA that has multiple jobs, and have the second job (installation) run only if the first job (uninstall) has completed successfully.

**Comment by WadeBarnes** [comment]
Is this the PR that resolved this ticket?  https://github.com/bcgov/trust-over-ip-configurations/pull/151

**Comment by rajpalc7** [comment]
yes wade, our latest PR resolved this ticket as well
