### ISSUE TITLE
Add banners to dev/test deployments of Traction

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#125]
Add configuration and redeploy Traction instances in `dev` and `test` to include information about the environment:
- For `dev` set the message to `Development Instance`
- For `test` set the message to `Test Instance`

**Comment by loneil** [comment]
I added a "DEV Environment" banner in the dev one but can feel free to change that to any other text as needed.

We can add the test value in on the PR going to modify test here
https://github.com/bcgov/trust-over-ip-configurations/pull/163

**Comment by esune** [comment]
> I added a "DEV Environment" banner in the dev one but can feel free to change that to any other text as needed.
> 
> Can add the test value in on the PR going to modify test here [bcgov/trust-over-ip-configurations#163](https://github.com/bcgov/trust-over-ip-configurations/pull/163) (or once it's merged in it will contain the UI section of the helm chart that you can do a PR to)

That looks good, thanks! @popkinj is this ticket still open or can we close it now?

**Comment by popkinj** [comment]
I think @loneil took care of it. So maybe ask them. :)

**Comment by loneil** [comment]
Test still needs doing. Once this pull request is merged we can make subsequent changes to the `ui` block of the values to add it
https://github.com/bcgov/trust-over-ip-configurations/pull/163

**Comment by loneil** [comment]
Added a bit ago on https://github.com/bcgov/trust-over-ip-configurations/pull/166
