### ISSUE TITLE
Update Sandbox banner to include next reset date

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#126]
Update the sandbox reset/redeploy GHA to include the top banner message.

The message should be in the format: `Sandbox. This environment will be next reset on Nov 1st 2023 @ 2am PST`, or something similarly meaningful.

**Comment by swcurran** [comment]
Suggest instead: `BC Gov Traction Sandbox: This environment is normally reset on the 1st and 15th of each month. It was last reset on January 1, 2024.`, where the date at the end is dynamically inserted.  Its best to know the date of the last reset because:

- we may have to reset on dates other than the 1st and 15th.
- if a user is wondering why the can’t get in, they might see that a reset was done since they last used it.

**Comment by esune** [comment]
My only concern is with the verbosity of the message, since we will have limited space in the banner (unless we implement text scrolling too, that is).

**Comment by loneil** [comment]
Is this to programmatically know the previous or next reset date? The message will pull from the values file, which should be represented in the file in the repo. So would someone update it every 2 weeks manually, or is there intended to be a mechanism where the GHA that does the reset programmatically commits a change to sandbox values or something else like that?

Would rigging any of that be worth the work over just using a generic message?

**Comment by esune** [comment]
If we can be more specific about last/next reset it would be great. I was thinking we could use a bash script to generate the message string (with the dates) and then inject it OVER the values file using the `--set-string` argument

**Comment by WadeBarnes** [comment]
Can that be updated automatically by the GitHub workflows that perform the reset?

**Comment by esune** [comment]
> Can that be updated automatically by the GitHub workflows that perform the reset? I see that has already been suggested.

Yes, that is the idea: the workflow compiles the new string value and sets it for the deployment using `--set-string` when installing the chart.

**Comment by popkinj** [comment]
Couldn't we just have a constant like... Reset every Sunday night at 11pm... Then have the front end do the math of "Will reset in 2 days and 4 hours"?

**Comment by popkinj** [comment]
> Update the sandbox reset/redeploy GHA to include the top banner message.
> 
> The message should be in the format: `Sandbox. This environment will be next reset on Nov 1st 2023 @ 2am PST`, or something similarly meaningful.

Is the reset always at 2am?
