### ISSUE TITLE
Add notifications to sandbox refresh GHA

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#128]
The Traction Sandbox refresh GHA developed for #123 does not currently provide failure notifications to teh SRE team, but rather to the user that last modified the workflow (as per [GitHub documentation](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs)).

It would be nice to receive notifications in the `dts-notifications` channel in Rocket.Chat so that more people in the team can have visibility.

Ideally, notifications would be dispatched when:
- the Sandbox is successfully reset
- an error was encountered and the sandbox reset did not complete

**Comment by esune** [comment]
@WadeBarnes @i5okie please chime in if you have ideas or resources to provide about sending notifications from GHA workflow runs to Rocket.Chat

**Comment by i5okie** [comment]
There is this older GHA: https://github.com/marketplace/actions/rocket-chat-notification
It hasn't been updated since 2019, but might be worth testing in our workflow.

If it works, great. If not, we could evaluate how long it'd take to update it to work for us.
