### ISSUE TITLE
Traction Snadbox GHA is failing to execute 

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#129]
The Traction Sandbox reset GHA is failing to execute because of an expired token: https://github.com/bcgov/trust-over-ip-configurations/actions/runs/6408487629

This needs to be resolved ASAP.

**Comment by rajpalc7** [comment]
https://github.com/bcgov/trust-over-ip-configurations/actions/runs/6409140258

Hi Emiliano,
This is fixed now, I just needed to update the service account token just like I did with my fork repo and give the admin permission to the service account for bc0192-test env.
