### ISSUE TITLE
Add backup container to vc-authn deployment

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#134]
Add backups to dev/test/prod deployments of the new VC-AuthN 2.0 instances.

Configurations should be stored in this repository https://github.com/bcgov/dts-backup-configurations under a new root folder `dts-toip`. Look under the `dts-demo` for an example of MongoDB backup container,

**Comment by i5okie** [comment]
PR to upgrade scripts to work with MongoDB Version 6+:
https://github.com/BCDevOps/backup-container/pull/116

**Comment by i5okie** [comment]
Deployed backup-mongo to `test` and `prod` environments.
Both have been tested to complete the backup, and verification of the backup.

**Comment by i5okie** [comment]
PR with deploy values:
https://github.com/bcgov/dts-backup-configurations/pull/17

**Comment by i5okie** [comment]
blocked by: https://github.com/BCDevOps/backup-container/pull/116

**Comment by WadeBarnes** [comment]
> blocked by: [BCDevOps/backup-container#116](https://github.com/BCDevOps/backup-container/pull/116)

This PR has been merged and a new version has been released.
