### ISSUE TITLE
Switch sandbox/dev traction instances to use new DITP endorser

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#135]
- [x] Switch sandbox, dev instances to use the auto-everything DIT endorser
- [ ] Decommission existing `tools` endorser

**Comment by esune** [comment]
@loneil this is the issue to track the decommissioning of the tools endorser FYI

**Comment by loneil** [comment]
Dev switched over to new Tools endorser. I cut over all existing tenant connections to the new one.

Old Tools endorser turned off, will uninstall it completely next week some time.
