### ISSUE TITLE
Traction Sandbox refresh action failure and unplanned trigger

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#137]
It looks like the GHA that takes care of refreshing the Sandbox instance of traction is triggering every time a PR is merged, which is not the desired behaviour. See: https://github.com/bcgov/trust-over-ip-configurations/actions/runs/6712985673

Additionally, the installation failed on the last run (same link as above).

**Comment by popkinj** [comment]
Hmmmm :thinking: 
Could this have something to do with my previous merge? I'm not seeing a lot for logs. Can dig in further if nobody has found anything.

**Comment by esune** [comment]
Resolved in https://github.com/bcgov/trust-over-ip-configurations/pull/164
