### ISSUE TITLE
Deploy IDIM pre-production agent

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#143]
IDIM needs a pre-production agent to be deployed for load/integration testing purposes.

**Comment by WadeBarnes** [comment]
Based on this ticket `PreProd` is a `test` environment; https://github.com/bcgov/trust-over-ip-configurations/issues/79

Pulled the specific details.

| OpenShift Workspace | IDIM Environment | ACA-Py Name | Ledger |
| --- | --- | --- | --- | 
| Test | PreProd | PreProd | CANdy-Test |

**Comment by WadeBarnes** [comment]
Related PR; https://github.com/bcgov/trust-over-ip-configurations/pull/172

**Comment by WadeBarnes** [comment]
The new agent has been configured and wired up to the CANdy-Test - Government of British Columbia - Endorser Service.
- https://candyscan.idlab.org/tx/CANDY_TEST/domain/105

I'll contact @marcos-carretero privately to exchange the credentials.

**Comment by WadeBarnes** [comment]
API keys handed off to the IDIM team.  Calling this done.  Working with @marcos-carretero and team to connect their controller.
