### ISSUE TITLE
Remove agent governance link from traction sandbox

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#144]
Remove the reference to the Agent Service governance from the Sandbox deployment (see screenshot for reference).

![image](https://github.com/bcgov/DITP-DevOps/assets/2395873/6325c7b8-c761-4969-af51-b52ecbc17b88)

**Comment by swcurran** [comment]
That’s a very blank image…

**Comment by esune** [comment]
> That’s a very blank image…

Not sure what happened between the upload and the publishing - fixed.

**Comment by loneil** [comment]
Is there anything that's supposed to go in it's place for the Sandbox environment

**Comment by esune** [comment]
> Is there anything that's supposed to go in it's place for the Sandbox environment

No, at least not currently - there is no service agreement of sorts so removing it completely would be best. If not possible, I guess a sentence among the lines of "No service agreement available" could do?

**Comment by loneil** [comment]
Traction Tenant UI adding Helm values (these were missing) to control config is in https://github.com/bcgov/traction/pull/1024

The Sandbox values are set in https://github.com/bcgov/trust-over-ip-configurations/pull/185
