### ISSUE TITLE
Prepare to run an OpenShift Traction Load Test

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#148]
Create Sandbox Traction tenants for an issuer and a verifier, configure them as per the Aries Akrida "Quickstart", and adjust the environment (.env) configuration to point to those instances, and the OpenShift "dev" mediator.  Run low load tests to show that the environment is operational.

A guide for setting up a Sandbox Traction tenant is available [here](https://github.com/bcgov/traction/blob/main/docs/traction-anoncreds-workshop.md).

Request access to the dev mediator from @WadeBarnes. 

This is the second step of the load test generator plan discussed in a meeting 2023.12.18, and summarized in this [presentation](https://docs.google.com/presentation/d/1WOhr-j-9gHsTh02DBPTLm8m6xt-rrUoGQso3iOz3yWM/edit?usp=sharing).

**Comment by WadeBarnes** [comment]
Delivered a mediator invite to @Gavinok

**Comment by Gavinok** [comment]
As of now `locustMediatorIssue.py`, `locustMediatorPing.py`, and `locustMediatorMsg.py` are working. `locustMediatorPresentProof.py` on the other hand routinely fails during the `presentation_exchange` step with the error
```
Exception('Request was not successful: ', b'400: Record not found: connection/fc302da8-a400-4315-905b-399a7f6a523b.')
```

**Comment by swcurran** [comment]
Completed — able to get to over 200/issuances per minute.
