### ISSUE TITLE
Fix the links in our sysdig alerts

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#15]
Fix the following links in our Sysdig alerts:
- The `Dashboard` link.  The current links direct the user to an undefined rocket.chat channel, rather than the Sysdig dashboard containing the associated information.
- The "alert details" link.  The links do work, however you need to be logged into sysdig (an expected step), AND be viewing the correct sysdig team (unexpected step) to be directed to the alert trigger details.  The links should automatically direct you to the correct sysdig team and alert notification.

**Comment by WadeBarnes** [comment]
@rajpalc7, I've been monitoring the dashboard links and they seem to be working well now.  Have you heard back about the links to the alerts?  If not, please create a separate ticket for yourself to track the issue.

**Comment by rajpalc7** [comment]
Hi @WadeBarnes , Shelley is still on PTO. Will follow up with her once she is back. Will create a separate ticket for tracking.

**Comment by WadeBarnes** [comment]
@rajpalc7, When you've created the new ticket can you put a link to it here please.

**Comment by rajpalc7** [comment]
Sure @WadeBarnes - https://app.zenhub.com/workspaces/dts-deployments-61dccb768e14c5001fea635a/issues/bcgov/ditp-devops/25  

Here is the link for the ticket
