### ISSUE TITLE
OrgBook - Investigate periodic spikes in search engine CPU usage

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#150]
Starting January 3rd 2024 - 4:20pm we started to experience CPU spikes to 60% every four hours.  These spikes do not appear to be related to query volume, rather a specific query pattern which is different than the known and blocked one.

![Image](https://github.com/bcgov/DITP-DevOps/assets/10504350/f7246661-0982-499a-85b4-31a623f46cfd)

These spikes are continuing to occur on a periodic basis.

Note the level of the spikes is reduced due to the down sampling of the wider time scale in this graph:
![Image](https://github.com/bcgov/DITP-DevOps/assets/10504350/37810c5a-62d1-45ba-924c-a4dc94be1f36)

![Image](https://github.com/bcgov/DITP-DevOps/assets/10504350/ea23430f-a7f8-42be-a69f-b607a14bc62e)

Investigate and identify the query pattern responsible for these spikes and determine if it's a pattern we should be blocking.  For the moment this activity is not adversely affecting performance or service levels.

**Comment by WadeBarnes** [comment]
A closer look at one of the recent spikes:
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/3357a66c-2b6f-4f6a-8470-5f25bc596564)
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/d3756f10-7320-4197-a4cb-394a1b624357)

**Comment by WadeBarnes** [comment]
The queries during these periods appear to be performing paging to the level we allow.  I've adjusted the expression filtering to limit things a bit more to see if that helps.

**Comment by WadeBarnes** [comment]
The changes helped narrow the window:
![Image](https://github.com/bcgov/DITP-DevOps/assets/10504350/37926c23-e17e-4b3c-926d-d038c7367463)
![Image](https://github.com/bcgov/DITP-DevOps/assets/10504350/e125d327-f167-4cfb-a6d4-4dc60147a4e8)

**Comment by WadeBarnes** [comment]
The load is definitely related to paging queries.

**Comment by swcurran** [comment]
Almost certainly, these issues are coming from a known entity to BC Gov (I’ll leave off the name), who is trying to use OrgBook as a way to maintain s full list of all BC registred entities.  They are meeting with BC Registries tomorrow to talk about how to get the information in other ways.  Since they want to maintain their database to be as accurate as possible, I’m sure they will continue to work on how to scrape the data.

**Comment by WadeBarnes** [comment]
The IP addresses associated to these particular queries are globally distributed, so I'm skeptical that's the source.  I've been tracking another query pattern that I suspect is related to what you're talking about, but that query pattern does not use paging, and therefore does not put much load on the search engine.  Looks like this:

![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/e6e0ba70-7f4e-427f-95f7-66bf7af597f0)

**Comment by WadeBarnes** [comment]
The adjustments to the expression filtering greatly reduced the duration of the CPU spikes, and you can see this from the 1D view here.  It shows up as a reduction in CPU use since the data is down sampled.
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/95b13208-af56-4204-a0a4-a6f6794ff0fd)

Zooming in you can see this is just a reduction in the duration:
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/f811ffb8-ec08-491c-8f93-ffb1b51b9354)
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/55c597a3-8123-42e0-80bd-5c307bd60852)

Interestingly this also has appeared to detour some of the unwanted traffic.  Though we've seen this traffic drop off and pick up again before, the reduction correlates with the updated to the expression filtering quite well.
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/9fc5e2e5-1626-44a7-b82d-6b09837d137d)

**Comment by WadeBarnes** [comment]
Additional query patterns have been identified and added to the expression filtering.

**Comment by WadeBarnes** [comment]
The updates to the expression filters got things under control.
