### ISSUE TITLE
Review production agent configuration

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#152]
IDIM agent was running a single instance in `prod`, when we've had it configured to run three instances.  That instance was interrupted by platform updates, causing a 6 minute outage for the service.

Review the configuration of the production services to ensure they are HA.

**Comment by WadeBarnes** [comment]
During the review I found the old `vc-authn` instances were still running in `dev`, `test`, and `prod`.  After talking with @esune I've scaled these down to see if anyone complains.  All services should be using the new instances now.

**Comment by WadeBarnes** [comment]
The configuration of the following agents has been updated to include HPAs and anti-affinity rules to ensure a minimum number of pods are running and they are explicitly distributed across compute nodes.
- A2A (Demo A2A issuer), in `dev` and `test` only
- BCReg, in `dev` only
- BC VC Pilot Issuer
- IDIM Issuers
- LSBC Issuers

**Comment by WadeBarnes** [comment]
@esune, Do you also know the current operational status of the LCRB issuers?  They already have HPA configurations but are all set to min 1 max 1 and they are only operational in `dev` and `test`, the `prod` instance is scaled to 0.

**Comment by WadeBarnes** [comment]
Also reviewed the mediator and endorser instance configurations, they both have HPA configurations and are scaled appropriately.

**Comment by WadeBarnes** [comment]
BC Wallet Demo has HPA configurations and is scaled appropriately.

**Comment by WadeBarnes** [comment]
Review of the following environments is complete (pending any feedback):
- Digital Trust Shared Services
- Digital Trust Services Trust Over IP
- Digital Trust Demo Apps

**Comment by esune** [comment]
@WadeBarnes I am not sure on whether the LCRB and BuyBC issuer agents are currently being used - I suspect they only issue credentials sporadically, if any.

**Comment by WadeBarnes** [comment]
@esune, What's the best way to find out?  I don't have contacts for either.

**Comment by esune** [comment]
> @esune, What's the best way to find out? I don't have contacts for either.

I'll try to track things down

**Comment by esune** [comment]
Both LCRB and BuyBC agents seem to not be in use right now. We will spin them down and see if we receive inquiries/complaints and act accordingly.

@WadeBarnes if these were the last two agents requiring review we might be able to close this issue.
