### ISSUE TITLE
Decommission old vc-authn instances in the Digital Trust Services Trust Over IP (e79518) environments

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#154]
The `vc-authn` instances in the Digital Trust Services Trust Over IP (e79518) environments have been scaled down to wait out a scream test period.

If no one complains (screams), the instances can be safely deleted in 3-4 weeks.  This extended period is to account for the fact that the demo services that could still be connected to the instances are not accessed on a regular basis.

**Comment by esune** [comment]
@WadeBarnes I think we are good to go with removing these deployments now - can you confirm? If so I'll go ahead and free some resources.

**Comment by WadeBarnes** [comment]
Confirmed.

**Comment by esune** [comment]
Deployments have been purged and resources released.
