### ISSUE TITLE
Review Digital Ocean Apps

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#159]
Following is the list of applications we host on Digital Ocean.

Do we want to decommission any of them?

~Of those we want to keep, can we scale the resources to minimal levels?~
 - Based on a review of the resources the droplets are all resourced appropriately.  i.e. They are already making full use of the allocated resources, so cannot be scaled down any further. 

## Apps

- [x] bcdigitaltrust.info - **Decommission - content migrated to its new home**
  - https://bcdigitaltrust.info/
    - The content for the `digital-trust` section of the `https://digital.gov.bc.ca` website; https://digital.gov.bc.ca/digital-trust
  -  2 vCPU / 2GB Memory/ 60 GB Disk
  - $18.00 / month
  - Long term plan is to migrate the content to and integrate it directly with the main `digital.gov.bc.ca` site.
- [x] icatagent - **Decommission**
  - Recommendation - Decommission 
  - Agentbook (the original version of Aries-VCR, Indy Catalyst) - http://agentbook.vonx.io/
  - [References](https://www.google.com/search?q=%22agentbook.vonx.io%22&rlz=1C1CHBF_enCA985CA985&oq=%22agentbook.vonx.io%22&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRiPAtIBCjEzNDk0ajBqMTWoAgCwAgA&sourceid=chrome&ie=UTF-8)
  - 1 vCPU / 1GB Memory/ 25 GB Disk
  - Uses about half of it's available resources when active.
  - $6.00 / month
- [x] dev-dflow-von-network   - **Decommission**
  - Recommendation - Decommission.  Redirect to a page indicating the ledger has been decommissioned and to use BCovrin Test as the replacement.
  - [GreenLight Dev Ledger](http://dev.greenlight.bcovrin.vonx.io/)
    - As of 2024.01.30 - Last used: 2024.01.30 (232378 txns)
    - *This ledger is no longer used from a BC Gov perspective.  However it is referenced in some demo/tutorial documentation.  See references link for details.*
  - [References](https://www.google.com/search?q=%22dev.greenlight.bcovrin.vonx.io%22&sca_esv=8add31af34f47e86&rlz=1C1CHBF_enCA985CA985&sxsrf=ACQVn098oH-1u3wbfxqvyfEptNzFEiUh0w%3A1706626813923&ei=_Q65ZeL_N-jb0PEP2Ny10AE&ved=0ahUKEwii8oeosIWEAxXoLTQIHVhuDRoQ4dUDCBA&uact=5&oq=%22dev.greenlight.bcovrin.vonx.io%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiICJkZXYuZ3JlZW5saWdodC5iY292cmluLnZvbnguaW8iSOBNUMgWWJxLcAF4AJABAJgBgQGgAY8FqgEDOC4xuAEDyAEA-AEC-AEB4gMEGAEgQYgGAQ&sclient=gws-wiz-serp#ip=1)
  -  2 vCPU / 2GB Memory/ 60 GB Disk
  - Using 40% CPU, and 80% Memory
  - $18.00 / month
- [x] dflow-von-network - **Decommission**
  - Recommendation - Decommission.  Redirect to a page indicating the ledger has been decommissioned and to use BCovrin Test as the replacement.
  - [GreenLight Ledger](http://greenlight.bcovrin.vonx.io/)
    - As of 2024.01.30 - Last used: 2024.01.26 (15225 txns)
    - *This ledger is no longer used from a BC Gov perspective.  However it is referenced in some demo/tutorial documentation.  See references link for details.*
  - [References](https://www.google.com/search?q=%22greenlight.bcovrin.vonx.io%22&sca_esv=8add31af34f47e86&rlz=1C1CHBF_enCA985CA985&sxsrf=ACQVn09rsjt6pMQupb7KRUB3xmhl1mYzfw%3A1706626894000&ei=TQ-5ZbHHPKyC0PEP95CY-AM&ved=0ahUKEwjxoZ_OsIWEAxUsATQIHXcIBj8Q4dUDCBA&uact=5&oq=%22greenlight.bcovrin.vonx.io%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiHCJncmVlbmxpZ2h0LmJjb3ZyaW4udm9ueC5pbyJI7BZQjxBYkBFwA3gAkAEAmAFIoAGEAaoBATK4AQPIAQD4AQHiAwQYASBBiAYB&sclient=gws-wiz-serp)
  - 2 vCPU / 2GB Memory/ 60 GB Disk
  - Using 40% CPU, and 90% Memory
  - $18.00 / month
- [x] von-network - **Decommission**
  - Recommendation - Keep
  - [BCovrin Dev](http://dev.bcovrin.vonx.io/)
    - As of 2024.01.30 - Last used: 2024.01.30 (22005 txns)
    - *From a BC Gov perspective this ledger is used for testing purposes and demo applications.  It is also associated with the BC Reg and OrgBook `dev` environments.*
  - [References](https://www.google.com/search?q=%22dev.bcovrin.vonx.io%22&sca_esv=8add31af34f47e86&rlz=1C1CHBF_enCA985CA985&sxsrf=ACQVn0_sSrkTk7UKfcwZjanXA7DpAez4ig%3A1706626974208&ei=ng-5ZY2sDPrJ0PEPw_at6AY&ved=0ahUKEwiN8770sIWEAxX6JDQIHUN7C20Q4dUDCBA&uact=5&oq=%22dev.bcovrin.vonx.io%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiFSJkZXYuYmNvdnJpbi52b254LmlvIkiwEVDzClj5DHACeACQAQCYAWmgAY4CqgEDMi4xuAEDyAEA-AEB4gMEGAEgQYgGAQ&sclient=gws-wiz-serp)
  - 2 vCPU / 2GB Memory/ 60 GB Disk
  - Using 40% CPU, and 90% Memory
  - $18.00 / month
- [x] TEST-von-network - **Keep!  Actively used.  Do NOT adjust resources.**
  - Recommendation - Keep
  - [BCovrin Test](http://test.bcovrin.vonx.io/)
    - **Actively used**
    - *From a BC Gov perspective this ledger is used for testing purposes and demo applications.  It is also associated with the BC Reg and OrgBook `test` environments.*
  - [References](https://www.google.com/search?q=%22test.bcovrin.vonx.io%22&sca_esv=8add31af34f47e86&rlz=1C1CHBF_enCA985CA985&sxsrf=ACQVn0_gblLR0Ztqj6rM3blL-ctO7R7YQw%3A1706627048956&ei=6A-5ZcP9OY2o0PEPoqCj0AQ&ved=0ahUKEwjDkZGYsYWEAxUNFDQIHSLQCEoQ4dUDCBA&uact=5&oq=%22test.bcovrin.vonx.io%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiFiJ0ZXN0LmJjb3ZyaW4udm9ueC5pbyJIgBFQuQlY0gxwAngAkAEAmAFZoAG2AqoBATS4AQPIAQD4AQHiAwQYASBBiAYB&sclient=gws-wiz-serp)
  - 4 vCPU / 8GB Memory/ 160 GB Disk
  - $48.00 / month
- [x] PROD-von-network - **Decommission**
  - Recommendation - Decommission.  Redirect to a page indicating the ledger has been decommissioned and to use BCovrin Test as the replacement.
  - [BCovrin](http://prod.bcovrin.vonx.io/)
    - As of 2024.01.30 - Last used: 2024.01.13 (894 txns)
    - *Not actively used by BC Gov demos and services, though we do have an Endorser Service instance connected to it for testing.  This is/was used as a placeholder for Sovrin MainNet for applications integrating with OrgBook that were not quite ready to go live. We've rarely used it in the past while.*
  - [References](https://www.google.com/search?q=%22prod.bcovrin.vonx.io%22&sca_esv=8add31af34f47e86&rlz=1C1CHBF_enCA985CA985&sxsrf=ACQVn082mEt_YszdKksXq1R4Glrxmr9llw%3A1706627012902&ei=xA-5ZcquNrPy0PEPhoWl0Ao&ved=0ahUKEwjKoPiGsYWEAxUzOTQIHYZCCaoQ4dUDCBA&uact=5&oq=%22prod.bcovrin.vonx.io%22&gs_lp=Egxnd3Mtd2l6LXNlcnAiFiJwcm9kLmJjb3ZyaW4udm9ueC5pbyJI8QxQlglY4AtwAngAkAEAmAFdoAHzAaoBATO4AQPIAQD4AQHiAwQYASBBiAYB&sclient=gws-wiz-serp)
  - 2 vCPU / 2GB Memory/ 60 GB Disk
  - Using 40% CPU, and 90% Memory
  - $18.00 / month

# Cleanup
- [x] Decommission Droplets - Scheduled for April 1st (no joke)
  - [x] Remove all snapshots and backups associated with the droplets being decommissioned.
  - [x] Delete the droplets
- [x] Update DNS Records
  - [x] Remove `agentbook`
  - [x] Remove `bcdigitaltrust.info` - externally managed
  - The extra BCovrin records can stay.

**Comment by WadeBarnes** [comment]
@swcurran, @esune, For review and discussion.

**Comment by WadeBarnes** [comment]
cc @jljordan42, @CharlesMacpherson

**Comment by alexgmetcalf** [comment]
> @alexgmetcalf, Could you validate the long term plan for the `bcdigitaltrust.info` site please?

We should be able to retire the need for it in the next quarter or so.

**Comment by swcurran** [comment]
@WadeBarnes — In addition to retriing the WordPress site (has the URL been removed from everywhere?), I’d like to close down all the unused services we have running, or at minimum scale down the ones that are rarely used.

![image](https://github.com/bcgov/DITP-DevOps/assets/1018050/efcc659d-b20e-4ce7-a426-5f66956870f6)

- What is icatagent?  I don’t even remember any more.
- I don’t think we have ever used/advertised Prod BCovrin, so let’s just take it down.
- dflow is referenced in a few places, but only one, so the other can/should be taken down.
   - Assuming we don’t care about the data already published on the ledgers (since it is just tutorials), could we just change the genesis file to be BCovrin Test so that it used that network?
- Is there effort in reducing the resources to minimize the costs of all but BCovrin Test (which is really the only one we need).  Does it take work to do all that.

Is there a place where we can see what URLs are referencing what resources?

Thanks

**Comment by WadeBarnes** [comment]
> * What is icatagent?  I don’t even remember any more.
> * I don’t think we have ever used/advertised Prod BCovrin, so let’s just take it down.
> * dflow is referenced in a few places, but only one, so the other can/should be taken down.
>   
>   * Assuming we don’t care about the data already published on the ledgers (since it is just tutorials), could we just change the genesis file to be BCovrin Test so that it used that network?
> * Is there effort in reducing the resources to minimize the costs of all but BCovrin Test (which is really the only one we need).  Does it take work to do all that.
> 
> Is there a place where we can see what URLs are referencing what resources?
> 
> Thanks

All of the URLs (or links to them) for the services are available in the description.  If you click in references, you will be taken to a google search for references to the given service you can review.  I also did a resource review on all the droplets, they are as small as they can be.  All info in the description.

**Comment by swcurran** [comment]
Sorry — I didn’t see the description :-).  The email I clicked on jump me right to the comment about bcdigitaltrust.info, and I didn’t scroll up.  I’ll review that and offer suggestions.

**Comment by esune** [comment]
Agentbook/icatagent was a VERY old demo we put together for IIW if I remember correctly, I would think by now it can be decommissioned as it is really, really old.

I am not sure what dFlow is still used for, I believe we decommissioned all of the demos using it in OpenShift so I would think the related services in DO can go as well?

Agreed that a production von-network won't be very useful and should be purged.
BCovrin `dev` is used by some demos/Traction instances for development purposes.

**Comment by WadeBarnes** [comment]
> Agentbook/icatagent was a VERY old demo we put together for IIW if I remember correctly, I would think by now it can be decommissioned as it is really, really old.

You are correct, this was one of our original demo apps that included messaging.

> I am not sure what dFlow is still used for, I believe we decommissioned all of the demos using it in OpenShift so I would think the related services in DO can go as well?

If you look at the details and links in the description, you'll see `dFlow` are the Greenlight ledgers.  History, they were originally created for the dFlow demo apps, which were later renamed to Greenlight.  These were the demos for the flow associated with the restaurant permit licensing.  That said, references to those ledgers made it into various documentation as you'll see in the reference links.  They are also being used, to a lesser scale than BCovrin Test, activity.  We do not use them for any of our demos but others following the demo docs do.

> Agreed that a production von-network won't be very useful and should be purged. BCovrin `dev` is used by some demos/Traction instances for development purposes.

BCovrin `Prod` is/was used as a placeholder for Sovrin MainNet for applications integrating with OrgBook that were not quite ready to go live.  We've rarely used it in the past while.

**Comment by WadeBarnes** [comment]
I've updated the descriptions with some additional usage information.

Of the ledgers, I think we should keep BCovrin Dev and BCovrin Test.  The others could be retired, and we could setup a redirect site for them that indicates the ledger has been decommissioned and recommend the use of BCovrin Test as the replacement.

**Comment by esune** [comment]
@WadeBarnes this is being worked on currently, correct (i.e.: BCovrin ledgers review)? If so I'll assign it to you and move to "In Progress"

**Comment by WadeBarnes** [comment]
`icatagent` and all of the BCovrin instances, other than BCovrin Test have been scaled down and will be decommissioned permanently on April 1st.  The DNS records for the BCovrin instances have been redirected to BCovrin Test.  Notices have been posted in two locations on both the Hyperledger and Open Wallet Foundation discord servers.

**Comment by WadeBarnes** [comment]
The content for https://digital.gov.bc.ca/digital-trust which was hosted on bcdigitaltrust.info migrated to it's new home yesterday afternoon.  bcdigitaltrust.info has been scaled down and will be decommissioned with the other droplets on April 1st.

**Comment by WadeBarnes** [comment]
Work here is complete.
