### ISSUE TITLE
Review ACS Reports

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#16]
Review ACS reports and come up with any necessary update plans.

- [ ] `backup` images
  - Would require the base image for the backup container to be upgraded.
  - Currently using a `centos/postgresql` image as the base image.  The centos base images are now deprecated.
  - We should consider moving to the official Postgres images for the base.  There are rhel based images available, but they require an account or token to get, which is fine if you're building the image on the platform.

- [ ] `database` images
  - Review and update (rebuild) from the latest base images.
  - Reviewed Orgbook environment.

- [ ] Orgbook `api` images
  - Update (rebuild) from the latest base image.

- [x] Orgbook `frontend` images
  - They are ok..

- [ ] `agent` images
  - Test out an image based on the `Docker.indy` build from this `aca-py` PR, https://github.com/hyperledger/aries-cloudagent-python/pull/1888.
  - To get a more up-to-date base image build the image using python 3.9.  The `aca-py` tests all seem to pass when run on python 3.9 images; https://github.com/WadeBarnes/aries-cloudagent-python/actions/runs/3528226011/jobs/5918100044

- [ ] `search-engine` images
  - Try upgrading Solr to v9.1.
  - This involves updating the https://github.com/bcgov/openshift-solr project to use v9.1 as the base image, and then rebuilding the search-engine images using the new base image.  Thorough testing needs to be done with the existing indexes, and Solr recommends rebuilding search indexes when upgrading between major releases.  That would require using the offline-indexing pods and swapping out the indexes.

**Comment by hiteshgh** [comment]
Will need to break down the outcomes in multiple stories/spikes

**Comment by WadeBarnes** [comment]
Closing this in favor of https://github.com/bcgov/DITP-DevOps/issues/158.  This issue has become a bit stale, but is referenced in the new ticket for reference.
