### ISSUE TITLE
Remove TAA/AMl from CANdy ledgers

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#161]
The CANdy ledgers have been set-up to require acceptance of TAA/AML upon first acces by a new author, however this step is not really necessary as there is/will be more governance around the CANdy endorsers aimed at enforcing requirements for write transactions.

The ledgers to audit and to have TAA/AMl disabled on are:
- [x] CANdy `dev`
  - No TAA or AML registered on this ledger.
  - https://candyscan.idlab.org/txs/CANDY_DEV/config?page=1&pageSize=50&filterTxNames=[%22TXN_AUTHOR_AGREEMENT%22,%22TXN_AUTHOR_AGREEMENT_AML%22]&sortFromRecent=true
- [ ] CANdy `test`
  - https://candyscan.idlab.org/txs/CANDY_TEST/config?page=1&pageSize=50&filterTxNames=[%22TXN_AUTHOR_AGREEMENT%22,%22TXN_AUTHOR_AGREEMENT_AML%22]&sortFromRecent=true
- [ ] CANdy `prod`
  - https://candyscan.idlab.org/txs/CANDY_PROD/config?page=1&pageSize=50&filterTxNames=[%22TXN_AUTHOR_AGREEMENT%22,%22TXN_AUTHOR_AGREEMENT_AML%22]&sortFromRecent=true

**Comment by WadeBarnes** [comment]
Disabling the TAA(s) is done using the `ledger disable-all-txn-author-agreements` command.  The resulting txn will require 2 Trustee signatures for the CANdy networks.

**Comment by WadeBarnes** [comment]
Transactions have been authored and entered into the `CANdy-Test - Ledger Transactions to Execute` and `CANdy-Prod - Ledger Transactions to Execute` google sheets and the Trustees have been notified signatures are required.

**Comment by cvarjao** [comment]
I've added my signature/approval to the transaction for CANDY-Prod

**Comment by CharlesMacpherson** [comment]
I've added my signature/approval to the transaction for CANDY-Prod

**Comment by swcurran** [comment]
I've added my signature to the CANdy-Test transaction.

**Comment by WadeBarnes** [comment]
The transactions have been executed.  The TAAs on CANdy-Test and CANdy-Prod have been deactivated.
- https://candyscan.idlab.org/tx/CANDY_TEST/config/61
- https://candyscan.idlab.org/tx/CANDY_PROD/config/61
