### ISSUE TITLE
Implement ArgoCD for DITP projects

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#167]
### Shared Goals
- Automate deployments of services to dev / test / prod
- Automate GitOps driven infrastructure (CrunchyBD, monitoring, other resources)
- Automate GitOps driven cluster access (team access RBAC, roles, role bindings, sysdig teams, etc)

### Projects
| Project Name | License Plate |
|---------|----------------|
| Traction | bc0192 |
| Digital Trust Services Over IP | a99fd4 |
| Digital Trust Monitoring Services | ca7f8f |

---
### Current Deployable Resources And Configurations

**Traction** GitHub [repo](https://github.com/bcgov/traction):
- `Traction` Helm chart
- `PR` deployment values
- `dev` deployment values

**Trust Over IP Configurations** [repo](https://github.com/bcgov/trust-over-ip-configurations/) :
- Traction `test`, `prod` deployment values
- vc-authn-oidc `dev`/`test`/`prod` deployment values
- Infrastructure / Monitoring stack -- Currently in PR [(https://github.com/bcgov/trust-over-ip-configurations/pull/181)](https://github.com/bcgov/trust-over-ip-configurations/pull/181)

**VC-AuthN-OIDC** [repo](https://github.com/bcgov/vc-authn-oidc/):
- `vc-authn-oidc` Helm Chart

**Comment by i5okie** [comment]
Helm chart updates have been validated with ArgoCD.

The next steps are to refactor existing GHA workflows to trigger the ArgoCD sync.
- https://github.com/bcgov/traction/issues/1198
- https://github.com/bcgov/vc-authn-oidc/issues/537

**Comment by i5okie** [comment]
Closing this issue as it has been broken down into the following tickets:
- https://github.com/bcgov/DITP-DevOps/issues/194
- https://github.com/bcgov/DITP-DevOps/issues/195
