### ISSUE TITLE
Traction test tenant request

### ISSUE THREAD

**Issue by PatStLouis** [bcgov/DITP-DevOps#176]
I would like to request a traction tenant for the stable test environment. This tenant will be used to deploy a TTTC instance and publish interoperability results on behalf of BCGov to the w3c-ccg. See #170 for details.

@swcurran @WadeBarnes @esune any further information required in this request?

**Comment by swcurran** [comment]
Have you created the request using the Traction UI?  If not — please do so (if you can…maybe you need an iDIR?).  Otherwise, we’ll get @Jsyro to do that for you, since he is part of the EMDT group.

**Comment by esune** [comment]
We need someone with an IDIR to put the request in - I can do it too if you want.

Did we land on whether we're deploying just one instance of this service, or two? If we deploy two (a "stable" and one to update if changes happen) I'd suggest we first integrate the existing deployment with `dev` and have `test` created for the next, more stable deployment.

**Comment by Jsyro** [comment]
I created a tenant request on TEST under Patrick's email address.

**Comment by esune** [comment]
> I created a tenant request on TEST under Patrick's email address.

Approved. @PatStLouis once checked-in let me know and I can authorize to connect to an endorser and we can set-up the connection to the appropriate ledger.

**Comment by PatStLouis** [comment]
Thanks for the help @esune @Jsyro
