### ISSUE TITLE
Traction database instances being heavily throttled in Traction (bc0192) environments

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#180]
The Traction database instances are being throttled at >60% on average.  Review and adjust the CPU resource allocations, primarily the CPU limit to reduce or eliminate the throttling.  The goal should be to reduce throttling to <25% on average.  For production an even lower average may be desirable.

These metrics can be easily reviewed using the Namespace Monitoring dashboard available through Grafana in our new monitoring stack.

**Comment by WadeBarnes** [comment]
## bc0192-dev
- CPU limit for `exporter` container in `traction-database-ha-*` stateful sets should be increased from 50m to 250m
- CPU limit for `pgbackrest` container in `traction-database-ha-*` stateful sets should be increased from 250m to 500m

## bc0192-test
- CPU limit for `exporter` container in `traction-database-ha-*` stateful sets should be increased from 50m to 250m
- CPU limit for `pgbackrest` container in `traction-database-ha-*` stateful sets should be increased from 250m to 500m

## bc0192-prod
- CPU limit for `exporter` container in `traction-database-ha-*` stateful sets should be increased from 50m to 250m
- CPU limit for `pgbackrest` container in `traction-database-ha-*` stateful sets should be increased from 250m to 500m

**Comment by WadeBarnes** [comment]
@i5okie, Where should these changes (values file) be made?

**Comment by i5okie** [comment]
These get applied directly to postgrescluster CR.
these live in trust-over-ip-configurations. Applied with kubectl apply -k bc0192/dev
From the kustomize directory.

Though, a couple have been applied with ArgoCD. In ministry-ditp-devops repo.

**Comment by i5okie** [comment]
- `postgres-cluster` base resource has been updated to reflect these changes, and pushed to the `ministry-gitops-ditp` repo.
- Changes have been applied to `bc0192-` `dev`, `test`, and `prod` via ArgoCD

**Comment by i5okie** [comment]
Changes successfully resolved the throttling issue.
