### ISSUE TITLE
Traction ACA-Py instances being heavily throttled in some Traction (bc0192) environments

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#181]
The Traction ACA-Py instances in some environment are being throttled at >30% on average.  Review and adjust the CPU resource allocations, primarily the CPU limit to reduce or eliminate the throttling.  The goal should be to reduce throttling to <25% on average.  For production an even lower average may be desirable.

These metrics can be easily reviewed using the Namespace Monitoring dashboard available through Grafana in our new monitoring stack.

**Comment by swcurran** [comment]
Questions from the raft of these issues:

- How are we detecting these situations?  Do we have notifications about throttling setup?  Presumably, if not we’ll add them?
- Any idea why these are coming to light now?  I thought we had a handle on the throttling and were happy with it.
- Is it a problem to ramp up the CPU as needed, or will that upset the Platform Team?
- Presumably, we just need to tweak the deployment scripts/configuration in a PR for the new resource needs and that will trigger a redeploy?

**Comment by WadeBarnes** [comment]
> * How are we detecting these situations?  Do we have notifications about throttling setup?  Presumably, if not we’ll add them?
> * Any idea why these are coming to light now?  I thought we had a handle on the throttling and were happy with it.

The issues are being detected through a review of our new monitoring dashboards.  I think you have access.  The Namespace Monitoring dashboard in particular has a graph specific to throttling that gives us a much better view than we had with any of the other tools available for the platform.  What's surfacing are the areas that were overlooked by our targeted testing and adjustments.

Adding alerts would be the next step.

> * Is it a problem to ramp up the CPU as needed, or will that upset the Platform Team?

The adjustments that need to be made should not upset the platform team.  They are concerned with over-reservation of resources, which we won't be doing.

> * Presumably, we just need to tweak the deployment scripts/configuration in a PR for the new resource needs and that will trigger a redeploy?

Correct, simple adjustments to the configuration.

**Comment by WadeBarnes** [comment]
The CPU limit on the Traction ACA-Py instances should be increased from `300m` to `500m - 1000m`.  Recommend `500m` for `dev`, `750m` for `test`, and `1000m` for `prod`.  For the most part the instances are not throttled, but they are mostly also idle.  When in use the throttling can spike significantly.

**Comment by WadeBarnes** [comment]
@i5okie, Where should these changes (values file) be made?

**Comment by i5okie** [comment]
for dev, right in traction repo.
for test and prod, trust-over-ip-configurations repo in kustomize folder.

**Comment by i5okie** [comment]
PR's with updated values:

[dev deployment}
https://github.com/bcgov/traction/pull/1131

[test and prod deployments]
https://github.com/bcgov/trust-over-ip-configurations/pull/207
