### ISSUE TITLE
Update Traction deployments

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#186]
A new release of Traction is available: https://github.com/bcgov/traction/releases/tag/v0.4.2

Please update the following deployments with the latest version:
- [x] `test`: update and inform @loneil / @esune for smoke testing and to confirm next environment can be updated
- [x] `prod`

**Comment by loneil** [comment]
Smoke test Traction TEST looks good. Used Tenant UI functions, Innkeeper.
Ran through Wallet Showcase Prod (that tenant is on Traction Test)
