### ISSUE TITLE
Update Issuer Kit based deployments

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#190]
These changes need to be rolled out to the various Issuer Kit deployments:
- https://github.com/bcgov/issuer-kit/pull/469

**Comment by esune** [comment]
`issuer-kit` deployments have mostly been decommissioned, closing this and replacing it with https://github.com/bcgov/trust-over-ip-configurations/issues/218 for the specific deployment(s) that need to be updated.
