### ISSUE TITLE
Helm values management

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#196]
In order to deploy our services using Helm charts, we need to store `values` files with details for each environment in a location that is accessible by our CD pipeline.

With the move to ArgoCD, it would make sense to store these files in the GitOps repository used to store the various configurations, however this presents a challenge since the GitOps repo is not publicly accessible and access is not going to be available to all team members.

One idea would be to store the values file for all environments in https://github.com/bcgov/trust-over-ip-configurations/tree/main/helm-values (currently Traction has the `dev` values in its repository) and trigger GitOps repo updates when they are updated, in a similar fashion to what happens with code releases in the source code repositories.

Ideally, we want to have:
- a standard strurcture followed by all projects
- public access to configurations, so that changes can be made/triggered by any team member and not just a subset (exception made for actions requiring approval, such as deployments to production)

c.c.: @i5okie @WadeBarnes for thoughts/feedback

**Comment by i5okie** [comment]
Values files for Traction and VC-AuthN-OIDC for dev, test, and prod environments are stored and maintained in `trust-over-ip-configurations` repo within the `services` directory. This directory is synchronized upstream to the `ministry-gitops-ditp` repository.

Related PR:
https://github.com/bcgov/trust-over-ip-configurations/pull/230
