### ISSUE TITLE
Enable DCO2

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#208]
Refer to this ticket: https://github.com/BCDevOps/devops-requests/issues/1715

Remaining repositories require a PR to be able to trigger DCO2 check and enable it as mandatory.

**Comment by WadeBarnes** [comment]
The switch to DCO-2 is complete for this repo.

All epos in the [list](https://github.com/BCDevOps/devops-requests/issues/1715#issuecomment-2427116171) has been updated other than as noted [here](https://github.com/BCDevOps/devops-requests/issues/1715#issuecomment-2476486548).

**Comment by esune** [comment]
Assigning to @amanji to trigger the DCO-2 check in `aries-oca-explorer`.

**Comment by swcurran** [comment]
FYI — I don’t have permissions on that repo to make the change. I can see the Settings, but only the “General - Access / Code and Automation” sections with minimal controls.  No way to invite other admins.  Looks like you have to do it @amanji .

**Comment by amanji** [comment]
Resolved by: https://github.com/bcgov/aries-oca-explorer/pull/31

**Comment by WadeBarnes** [comment]
All done
