### ISSUE TITLE
Investigate missing data on the DTS Service sysdig dashboards

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#22]
I know we were experiencing issues with the data on the `prod` instance of the DTS Service sysdig dashboard, but now all of them are affected.  The time the data went missing on the dashboards corresponds to when I was making resource adjustments in those environments.  Could it be the metrics where being picked recorded from specific pod instances rather than based more generic container names?

Please have a look that the metrics collection to track down the reason for the missing data.

**Comment by WadeBarnes** [comment]
@rajpalc7, While your are working on this issue you please be thinking about the items mentioned here; https://github.com/bcgov/DITP-DevOps/issues/24

**Comment by WadeBarnes** [comment]
This issue has not been resolved see my message here; https://github.com/bcgov/DITP-DevOps/issues/13#issuecomment-1337736350.  The metrics appear to be tracking named pod/container instances.

**Comment by rajpalc7** [comment]
@WadeBarnes - Closing this ticket as we have another ticket open related to this issue . - Investigate missing data on sysdig dashboards#24

**Comment by rajpalc7** [comment]
The agents were updated and all the missing data is available now.

**Comment by WadeBarnes** [comment]
Complete
