### ISSUE TITLE
Fix issues with OrgBook and BC Reg Dashboards

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#26]
The following issues were found while doing a review of https://github.com/bcgov/DITP-DevOps/issues/13

[Orgbook-Prod (Public)](https://app.sysdigcloud.com/#/shared/dashboard/5580c98c35db40038882be3d3157f4e4?last=21600)
- Missing a lot of data.  Bring this up with Dustin.

[Orgbook-Dev (Public)](https://app.sysdigcloud.com/#/shared/dashboard/c4f4df1761e040059951316d3ee75eb7?last=3600)
- Missing a lot of data.  Bring this up with Dustin.

[Orgbook-Backup (Public)](https://app.sysdigcloud.com/#/shared/dashboard/b0946fe758f74d1bafc8b8f624afecb0?last=3600)
- Missing a link to the related PVC dashboard.

[BCReg-Dev (Public)](https://app.sysdigcloud.com/#/dashboards/337084?last=3600&scope=kubernetes.namespace.name%20in%20%28%227cba16-dev%22%29)
- The link to the PVC dashboard links to a page the does not exist.
- Remove the `API endpoints` section at the bottom of the dashboard.
- Remove the `Controller-Primary` section at the bottom of the dashboard.

[BCReg-Test (Public)](https://app.sysdigcloud.com/#/shared/dashboard/aca9cb1f07b843ef8b042628f8e33223?last=3600)
- The link to the PVC dashboard links to a page the does not exist.
- Remove the `API endpoints` section at the bottom of the dashboard.
- Remove the `Controller-Primary` section at the bottom of the dashboard.

[BCReg-Prod (Public)](https://app.sysdigcloud.com/#/shared/dashboard/0251d2d9d5324810a65bcd0dff6191ff?last=3600)
- The link to the PVC dashboard links to a page the does not exist.
- Remove the `API endpoints` section at the bottom of the dashboard.
- Remove the `Controller-Primary` section at the bottom of the dashboard.

[BCReg-Backup (Public)](https://app.sysdigcloud.com/#/shared/dashboard/c422c11b982e4f8680faa19786f23eb4?last=3600)
- Missing a link to the related PVC dashboard.

**Comment by WadeBarnes** [comment]
> [Orgbook-Prod (Public)](https://app.sysdigcloud.com/#/shared/dashboard/5580c98c35db40038882be3d3157f4e4?last=21600)
> 
> * Missing a lot of data.  Bring this up with Dustin.
> 
> [Orgbook-Dev (Public)](https://app.sysdigcloud.com/#/shared/dashboard/c4f4df1761e040059951316d3ee75eb7?last=3600)
> 
> * Missing a lot of data.  Bring this up with Dustin.

@rajpalc7, What was the result of bringing these items up with Dustin?

**Comment by rajpalc7** [comment]
@WadeBarnes - https://github.com/bcgov/DITP-DevOps/issues/24

Yes we currently have a ongoing ticket open regarding this. What needs to be done is sysdig metrics tuning from Shelly's end (Platform team). Once the tuning is done I can do some testing from my side, try to fix the issue and close the tickets
