### ISSUE TITLE
BC Gov Endorser Service for Sovrin StagingNet and MainNet 

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#28]
AC

- [x] Create new (or repurpose existing) DIDs for use as Endorser DIDs on Sovrin StagingNet and MainNet.
  - [x] New DIDs generated
  - [x] Request to write DIDs to edgers submitted
  - [x] DIDs written to the ledgers.
    - [x] TestNet - https://indyscan.io/tx/SOVRIN_STAGINGNET/domain/341160
    - [x] MainNet - https://indyscan.io/tx/SOVRIN_MAINNET/domain/157225
- [x] Setup Endorser services to use the DIDs

Registering the affected agents with the endorser services (and demoting them to author) is defined as a separate set of tasks:
- https://github.com/bcgov/DITP-DevOps/issues/85
- https://github.com/bcgov/DITP-DevOps/issues/86

**Comment by WadeBarnes** [comment]
Currently updating DID audit (getDids) scripts.

**Comment by WadeBarnes** [comment]
DID audit (getDids) script updates complete.

**Comment by WadeBarnes** [comment]
Sovrin TestNet review:
- All of the DIDs we have registered on Sovrin TestNet were originally setup as endorsers for themselves.  There are none that would be appropriate to promote as a BC Government Endorser.
- Services include:
  - Email verification service for `dev`, `test`, and `prod`.
  - Open Verifiable Person for `dev`, `test`, and `prod`.
  - LSBC Issuer `dev` and `test`.

**Comment by WadeBarnes** [comment]
Sovrin MainNet review:
- The OrgBook (holder) DID, `NewAUq29E4jLJ5jMSxns3s`, has been used as an endorser for Buy BC and the GHG Emissions issuer.   Therefore, for consistency, it is the best candidate to be promoted to `Government of British Columbia - Endorser`.  The only problem with that is all of the OrgBook's credentials have been issued to that DID.
- All other DIDs have been setup as endorsers for themselves.
- Services include:
  - LSBC Issuer for `prod`.
  - OrgBook holder for `prod`.
  - BC Registries Agent Issuer (an OrgBook Issuer) for `prod`.
  - Mines Digital Trust, GHG Emissions Issuer (an OrgBook Issuer) for `prod`.
  - Mines Digital Trust, Mines Permitting Issuer (an OrgBook Issuer) for `prod`.
  - Buy BC Issuer (an OrgBook Issuer) for `prod`.

**Comment by WadeBarnes** [comment]
I think it's best if we just have two new purpose built endorser DIDs, one for Sovrin TestNet, and one for Sovrin MainNet, provisioned for use with the endorsers.  Then all existing DIDs can be demoted to authors.

**Comment by swcurran** [comment]
Agreed.

**Comment by WadeBarnes** [comment]
The endorsers for the Sovrin networks have been deployed.  They are not "active" at the moment, as I need to have the new DIDs registered with the Sovrin networks to complete the setup.

**Comment by WadeBarnes** [comment]
(re)Confirmed the DIDs for the TestNet and MainNet Sovrin endorsers have been written to the ledgers.
