### ISSUE TITLE
Deprecate and archive BCDevOps/go-crond

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#36]
Deprecate and archive the [BCDevOps/go-crond](https://github.com/BCDevOps/go-crond) repo.  The upstream repo has merged the changes that prompted the fork in the first place and has updated the project as well.

Add some documentation to this affect before archiving.

To be completed after https://github.com/BCDevOps/backup-container/issues/98

Review the use of `BCDevOps/go-crond` as it is more prevalent than I had thought.  Review the following searches and determine how best to proceed.

- [Use in DevOps Org](https://github.com/search?q=org%3ABCDevOps+go-crond&type=code)
- [Use in BCGov Org](https://github.com/search?q=org%3Abcgov+%22go-crond%22&type=Code)

Create a list of all affected repositories.  Create tickets for the DITP related repositories that need to be updated.  For the rest (other teams repositories) it may be best to make an announcement on Rocket.Chat with the list of the affected repositories.

**Comment by rajpalc7** [comment]
**List of all affected repositories**

https://github.com/BCDevOps/openshift-wiki

https://github.com/BCDevOps/backup-container

https://github.com/bcgov/von-bc-registries-audit

https://github.com/bcgov/met-public

https://github.com/bcgov/nr-arch-templates

https://github.com/bcgov/aries-vcr-issuer-controller

https://github.com/bcgov/jag-lcrb-carla-public

https://github.com/bcgov/eao-inspections-evidence-locker

https://github.com/bcgov/queue-management

https://github.com/bcgov/von-bc-registries-agent

https://github.com/bcgov/digital-journeys

https://github.com/bcgov/biohubbc-platform

https://github.com/bcgov/sso-keycloak

https://github.com/bcgov/sbc-pay

https://github.com/bcgov/met-public

https://github.com/bcgov/platform-developer-docs

https://github.com/bcgov/queue-management

https://github.com/bcgov/devhub-app-web

https://github.com/bcgov/tfrs

https://github.com/bcgov/eao-inspections-evidence-locker

https://github.com/bcgov/jag-lcrb-carla-public

https://github.com/bcgov/zeva

https://github.com/bcgov/biohubbc

https://github.com/bcgov/devhub-app-web

https://github.com/bcgov/github-optimization

https://github.com/bcgov/eao-inspections-evidence-locker

https://github.com/bcgov/von-bc-registries-agent-configurations

**Comment by WadeBarnes** [comment]
Following is a de-duplicated and categorized list of affected repos.

## List of all affected repositories

### DITP Managed Repos

- [ ] https://github.com/BCDevOps/backup-container
- [ ] https://github.com/bcgov/von-bc-registries-audit
- [ ] https://github.com/bcgov/aries-vcr-issuer-controller
- [ ] https://github.com/bcgov/von-bc-registries-agent
- [ ] https://github.com/bcgov/von-bc-registries-agent-configurations

### Others

- https://github.com/BCDevOps/openshift-wiki
- https://github.com/bcgov/met-public
- https://github.com/bcgov/nr-arch-templates
- https://github.com/bcgov/jag-lcrb-carla-public
- https://github.com/bcgov/eao-inspections-evidence-locker
- https://github.com/bcgov/queue-management
- https://github.com/bcgov/digital-journeys
- https://github.com/bcgov/biohubbc-platform
- https://github.com/bcgov/sso-keycloak
- https://github.com/bcgov/sbc-pay
- https://github.com/bcgov/platform-developer-docs
- https://github.com/bcgov/devhub-app-web
- https://github.com/bcgov/tfrs
- https://github.com/bcgov/zeva
- https://github.com/bcgov/biohubbc
- https://github.com/bcgov/github-optimization

**Comment by WadeBarnes** [comment]
@rajpalc7, I've reviewed own repos and identified what needs to be done.  For each of our repos above, please create a ticket for the identified work and then complete the work and submit PRs.  Thanks

**Comment by rajpalc7** [comment]
@WadeBarnes - Thanks Wade, PR has been submitted for all the repos now

**Comment by WadeBarnes** [comment]
@rajpalc7, PRs reviewed and merged.

**Comment by WadeBarnes** [comment]
Notification regarding the deprecation has been posted on Rocket.Chat; https://chat.developer.gov.bc.ca/channel/general?msg=E3JCP5Rd2CaGQeGcd

**Comment by rajpalc7** [comment]
@WadeBarnes PR approved

**Comment by WadeBarnes** [comment]
The [BCDevOps/go-crond](https://github.com/BCDevOps/go-crond) repo has been archived.

**Comment by WadeBarnes** [comment]
Complete
