### ISSUE TITLE
Add uptime monitoring for BC Wallet Showcase App

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#45]
Add uptime monitoring for the BC Wallet Showcase App in the `dev`, `test`, and `prod` environments.

URL endpoints to be monitored can be found here:
- `dev`: https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a99fd4-dev/routes?name=bc-wallet
  - I believe the `*law*` endpoints can be ignored as they don't seem to be connected to anything.  They likely should be deleted, but check with @wadeking98
- `test`: https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a99fd4-test/routes?name=bc-wallet
- `prod`: https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a99fd4-prod/routes?name=bc-wallet

There are three components to the application we want to monitor.  The proxy server (`bc-wallet-demo-proxy`), the server (`bc-wallet-demo-server`, which also acts as the agent), and the frontend website (`bc-wallet-demo-web`).

Start with adding a monitor for the public facing `prod` URL; https://digital.gov.bc.ca/digital-trust/showcase/

Add all checks to the appropriate sections of the status and sla pages.

**Comment by WadeBarnes** [comment]
@wadeking98, Is there some clean-up needed on the `bc-wallet-demo` resources in the `dev` environment.  See my comment above.

**Comment by wadeking98** [comment]
> @wadeking98, Is there some clean-up needed on the `bc-wallet-demo` resources in the `dev` environment. See my comment above.

Yes, I can clean it up. That's an artifact from when we have the showcase split into the lawyer and student showcases

**Comment by wadeking98** [comment]
# Routes to monitor:
## Dev:
- **Proxy**: https://bc-wallet-demo-agent-admin-dev.apps.silver.devops.gov.bc.ca
- **Agent**: https://bc-wallet-demo-agent-dev.apps.silver.devops.gov.bc.ca
- **Frontend**: https://bc-wallet-demo-dev.apps.silver.devops.gov.bc.ca
## Test:
- **Proxy**: https://bc-wallet-demo-agent-admin-test.apps.silver.devops.gov.bc.ca
- **Agent**: https://bc-wallet-demo-agent-test.apps.silver.devops.gov.bc.ca
- **Frontend**: https://bc-wallet-demo-test.apps.silver.devops.gov.bc.ca
## Prod:
- **Proxy**: https://bc-wallet-demo-agent-admin.apps.silver.devops.gov.bc.ca
- **Agent**: https://bc-wallet-demo-agent.apps.silver.devops.gov.bc.ca
- **Frontend**: https://bc-wallet-demo.apps.silver.devops.gov.bc.ca
## Prod public frontend URL:
- https://digital.gov.bc.ca/digital-trust/showcase

**Comment by WadeBarnes** [comment]
@wadeking98,  Could you have a look at the `bc-wallet-demo-web` in `test`.  Details provided in RC.

**Comment by rajpalc7** [comment]
@WadeBarnes - Hi Wade, both BC Wallet Demo Proxy and Web has been added as part of our checks, only endpoint is left at this point which needs to be discussed with Wade king. Once endpoint URL is working we can add it to checks and SLA pages and close this ticket

**Comment by WadeBarnes** [comment]
@rajpalc7, Please rename all `BC Wallet Demo` checks to `BC Wallet Showcase`.

**Comment by rajpalc7** [comment]
@WadeBarnes - Renaming is completed now

**Comment by WadeBarnes** [comment]
@wadeking98, What endpoints are available on the agent for monitoring?  The proxy looks like it's meant to be a proxy for the agent admin interface, and the agent endpoint is the client interface to the agent, is that correct?  Should we be monitoring the agent through the admin interface via the proxy?

Perhaps a quick meeting to discuss the network layout and options?

**Comment by WadeBarnes** [comment]
Monitoring is in place.  Other tickets deal with updates.
