### ISSUE TITLE
Add uptime monitoring for the BuyBC Agents and Controllers

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#46]
Add uptime monitoring for the BuyBC Agent and controllers in the `dev`, `test`, and `prod` environments.

URL endpoints to be monitored can be found here:

- `dev`: https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e79518-dev/routes?name=buybc
- `test`: https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e79518-test/routes?name=buybc
- `prod`: https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e79518-prod/routes?name=buybc

Depending on the version of `aca-py` the agents are running, we may need to upgrade them to be able to access the `/status/ready` endpoint on the agent without requiring the API key.

The endpoint on the controller you want to monitor is the `/health` endpoint.

**Comment by WadeBarnes** [comment]
@rajpalc7, For the Buy BC Controller checks, it would be better to expect the string `{"success":true}` to indicate the controller is working rather than explicitly matching `"success":false` to indicate the controller is down.  There are many conditions where the controller could be down and you would never explicitly match `"success":false`.  When possible you always want to look for the positive condition, that way any other response or behavior of the endpoint will be considered down.

When monitoring `aca-py` agents, you want to monitor the `/status/ready` endpoint (as indicated in the issue description) whenever possible.  This endpoint is a k8s compatible health endpoint that provides an indication of whether or not the agent is ready to accept requests.  You can use this single endpoint to monitor the agent, eliminating the need to monitor both of its client and agent endpoints.  The Buy BC agent instances are currently running an older version of `aca-py` that requires the use of an API key to authenticate with the status `/status/ready` endpoint.  So that leaves you with two options; use the API key to authenticate with the endpoint (not recommended), or upgrade the Buy BC instances to a newer version of `aca-py` that allows unauthenticated access to the `/status/ready` endpoint (recommended).

**Comment by hiteshgh** [comment]
Raj to update d blocker and other details

**Comment by esune** [comment]
@rajpalc7 could you please add a comment with the current status for this issue, and what is preventing it from being completed? Thank you!

**Comment by rajpalc7** [comment]
@esune - This ticket is completed now and can be reviewed by wade.
