### ISSUE TITLE
Add SysDig monitoring to OCP namespaces

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#47]
Add SysDig monitoring to the following OCP namespaces:

- [x] `e79518` - Digital Trust Services Trust Over IP
- [x] `a99fd4` - Digital Trust Demo Apps
- for `ca7f8f` - Digital Trust Monitoring Services, see https://github.com/bcgov/DITP-DevOps/issues/63

Please work on this in the order listed.  Feel free to split out into separate tickets, as you work on the different environments.

**Comment by WadeBarnes** [comment]
The SysDig teams for these environments have not been defined yet.  You need to create a SysDig team resource for each environment and apply it to the `tools` namespace.  Create the resources in the [sysdig](https://github.com/bcgov/DITP-DevOps/tree/main/sysdig) folder of this project.  An example you previously helped create can be found here; [4a9599-sysdigteam.yml](https://github.com/bcgov/DITP-DevOps/blob/main/sysdig/4a9599-sysdigteam.yml)

To apply the resources run the following command replacing <namespace> with the actual namespace name.  The commands must be run from the `sysdig` directory, and you must be logged into OCP.
```
~/git-repos/DITP-DevOps
$ cd sysdig/

~/git-repos/DITP-DevOps/sysdig
$ oc -n <namespace>-tools apply -f <namespace>-sysdigteam.yml
```

For Exmaple:
```
~/git-repos/DITP-DevOps
$ cd sysdig/

~/git-repos/DITP-DevOps/sysdig
$ oc -n 4a9599-tools apply -f 4a9599-sysdigteam.yml
```

Additional resources can be found here; https://docs.developer.gov.bc.ca/sysdig-monitor-setup-team/

While you're doing this, please add a ReadMe.bd document to the `sysdig` folder providing a summary of the steps and links to the supplied resource.

**Comment by hiteshgh** [comment]
pending read me document

**Comment by WadeBarnes** [comment]
Closing this ticket as complete.  https://github.com/bcgov/DITP-DevOps/issues/63 is open to track the completion for that namespace.
