### ISSUE TITLE
Add Sysdig Container Alerts to all monitored namespace and all environments

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#48]
Using the example Alert Dustin created for us (https://app.sysdigcloud.com/#/alerts/rules?alertId=14505300&direction=asc&sortBy=name).  Add similar alerts to all monitored namespaces and all environments.

We want to be alerted when the containers are in any of the following states for too long:
- ContainerCreating - Which Dustin's example does.
- ImagePullErr
- CrashLoopBackOff

Also have a look at some of the other alerts in the  Alerts > Library > Kubernetes section.  Ones of interest are:
- [Kubernetes] Pod Container Terminated With Error
- [Kubernetes] Node Readiness Flapping
- [Kubernetes] Init Container Waiting For a Long Time
- [Kubernetes] Init Container Terminated With Error
- [Kubernetes] Container Restarting

**Comment by WadeBarnes** [comment]
@rajpalc7, In the few namespaces that define some of these alerts I'm noticing in some cases the alerts are defined more then once for a given namespace, for example twice for the dev namespace.  Is it possible to define the alerts once so they cover `dev`, `test`, and `prod`?  This would be way easier to maintain.

**Comment by esune** [comment]
@rajpalc7 could you please add a comment with the current status for this issue, and what is preventing it from being completed? Thank you!

**Comment by rajpalc7** [comment]
@esune - These all alerts are completed now and set-up successfully. Wade and I were on call to test them. I will let wade review them.

**Comment by rajpalc7** [comment]
Sorry @WadeBarnes and @esune - to not give you guys enough updates and context regarding this ticket. So far I have been call with sysdig support engineers from past few days working 10:30-12am at night and so far they have themselves not figured out why sysdig is not able to trigger two alerts related to `container creating` alert and `pod terminated error` . They have told me they will need some time to re-produce this error in their lab and get back to me.


![image](https://user-images.githubusercontent.com/98990802/236354114-58440bfc-c631-49e8-8265-ae68ed677ee2.png)

**Comment by rajpalc7** [comment]
They also sent me an article which was not relevant to us as our cluster is on 4.11 . I have attached few screen shots to explain the on going conversation with sysdig support engineers.

![image](https://user-images.githubusercontent.com/98990802/236354419-e59f58e4-dc4d-493a-b151-516b0e160fd4.png)

**Comment by rajpalc7** [comment]
I have also tried to discuss this issue with Shelly from platform team but she has asked me to contact Dustin (Sysdig engineers) and dustin has opened a support ticket and sent me to engineers working in India and Singapore. Currently i am also working at nights and co-ordinating with Singapore engineer Giri and Thomas to resolve this issue ASAP.

**Comment by rajpalc7** [comment]
Sounds good Wade, I will try to keep our tickets up to date regularly.

**Comment by rajpalc7** [comment]
Followed up with Sysdig Support today, waiting for their response

**Comment by esune** [comment]
Blocked on waiting for a response from Sysdig to resolve the issue

**Comment by rajpalc7** [comment]
All the required alerts have been set-up successfully now.

**Comment by WadeBarnes** [comment]
@rajpalc7, Moving this back to in progress.  Following the platform updates we have several pods that were left in a non-running state.

For example:
a99fd4-dev - backup-postgres-18-scp28 - CreateContainerConfigError
a99fd4-test - backup-postgres-12-hd2pj - CreateContainerConfigError
a99fd4-prod - backup-postgres-26-6qsct - CreateContainerConfigError

Looking at the SysDig alerts for `a99fd4` it appears the alerts may already be defined (not confirmed), but they are disabled, so we won't get any notifications when they are triggered.

![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/7d58f1eb-578a-46d9-be44-3652892751f9)

Please review all alerts in all environments and ensure the necessary alerts are defined, enabled, and have notifications configured.

**Comment by WadeBarnes** [comment]
There are NO alerts defined for the Trust Over IP environments `e79518`.
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/3b6161d9-27f8-4309-80b9-56108fa3cd43)

**Comment by WadeBarnes** [comment]
There are NO alerts defined for the Monitoring Services environment `ca7f8f`:
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/512ad8eb-f1aa-4325-9c32-cc31652eb19d)

**Comment by rajpalc7** [comment]
Sounds good Wade, I thought you might test the alerts in a99fd4 namespace and if you are happy with them I can add all those alerts to other projects.

Those alerts were disabled because they were creating too much noise after testing. I will enable them now.

**Comment by rajpalc7** [comment]
I have added alerts to all the projects now. looks like that is already triggering few alerts.

**Comment by WadeBarnes** [comment]
Calling this done
