### ISSUE TITLE
Update duration on Pod Container Creating For a Long Time alerts

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#56]
Please review and adjust the duration setting on all the `Pod Container Creating For a Long Time` alerts.  We received a barrage of alerts from the OrgBook `dev` environment during a normal rollout.

The duration of the alert is set to 0 minutes, please change it to 1 minute.

Review the alert in all namespaces (not just the OrgBook namespace) and adjust all instances to the same duration.

**Comment by rajpalc7** [comment]
Thanks Wade, This has been fixed now.

**Comment by WadeBarnes** [comment]
@rajpalc7, please make sure you move tickets to In Progress when you start working on them and then to In Review when they are ready for review.

**Comment by WadeBarnes** [comment]
The intervals on the alerts look good now.  Found a related issue during the review and created a separate ticket for it.
