### ISSUE TITLE
Review Sysdig Alerts and ensure the enabled ones have a notification channel assigned

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#59]
All enabled alerts in all environments should be notifying the `#dts-sysdig-alerts` notification channel in rocket.chat.  If the alerts aren't posting to this channel, we'll never know there is an issue without explicitly looking.

The `dts-sysdig-alerts` notification channel is defined in `Settings` -> `Notification Channels` -> `dts-sysdig-alerts` in the `7cba16` and `8ad0ea` for reference.

SysDig Environments:

- [x] 4a9599
  - [x] Define the `dts-sysdig-alerts` notification channel
  - [x] Assign the `dts-sysdig-alerts` notification channel to all active alerts.

- [x] 7cba16
  - [x] Define the `dts-sysdig-alerts` notification channel
  - [x] Assign the `dts-sysdig-alerts` notification channel to the active alerts which don't have a notification channel defined.

- [x] 8ad0ea
  - [x] Define the `dts-sysdig-alerts` notification channel
  - [x] Assign the `dts-sysdig-alerts` notification channel to the active alerts which don't have a notification channel defined.

- [x] a99fd4
  - [x] Define the `dts-sysdig-alerts` notification channel
  - Assign the `dts-sysdig-alerts` notification channel to alerts as they are enabled.

- [x] ca7f8f
  - [x] Define the `dts-sysdig-alerts` notification channel
  - Assign the `dts-sysdig-alerts` notification channel to alerts as they are enabled.

- [x] e79518
  - [x] Define the `dts-sysdig-alerts` notification channel
  - Assign the `dts-sysdig-alerts` notification channel to alerts as they are enabled.

How to quickly tell if an alert has a notification channel assigned:

Any alert with this icon has a notification channel assigned:
![image](https://user-images.githubusercontent.com/10504350/227636570-c2be7a88-1093-4491-80b8-3e38e625c1d4.png)

For example `BCReg PVC 90% Capacity Dev` has a notification channel assigned and `BC Reg Prod Container down Alert` down does not:
![Image](https://user-images.githubusercontent.com/10504350/227635802-8f654963-4c99-497c-a08d-21198cacb970.png)

**Comment by esune** [comment]
@rajpalc7 could you please update the checklist above and add a comment with the current status for this issue, and what is preventing it from being completed? Thank you!

**Comment by rajpalc7** [comment]
@esune  - I am researching regarding the necessary alerts and triggering alerts we require for our project when any pods, nods and performance are affected that should give us an alert in sysdig channels. So far 6 alerts have been triggered successfully and i am working on 2 more. Once thats completed for a99fd4-teams, I will be able to clone these alerts for other projects and complete this ticket

**Comment by WadeBarnes** [comment]
Reviewed
