### ISSUE TITLE
Update monitoring for BC Wallet Showcase App

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#60]
The BC Wallet team is making some changes to the architecture of the BC Wallet Showcase app.  The changes have already started in `dev`.  The changes are not completely stable but once they are the changes will be rolling out to `test` and `prod` eventually.

The changes that have been made so far are:

- The agent endpoint has been removed; `https://bc-wallet-demo-agent-admin-dev.apps.silver.devops.gov.bc.ca`
- The backend URL has changes from `https://bc-wallet-demo-agent-dev.apps.silver.devops.gov.bc.ca` to `https://bc-wallet-demo-server-dev.apps.silver.devops.gov.bc.ca`

These changes have already been noticed by our uptime monitoring system; https://ditp.uptime.vonx.io/

Please update the uptime monitoring checks accordingly and plan to make similar changes to `test` and `prod`.

**Comment by WadeBarnes** [comment]
@rajpalc7, Please make the changes to the uptime monitoring checks.  @wadeking98 will let us know when things have stabilized.

**Comment by wadeking98** [comment]
@rajpalc7 and @WadeBarnes the URLs are stable now

**Comment by WadeBarnes** [comment]
@rajpalc7, Can you please have a look at this so we can clear the alert off our monitoring site; https://ditp.uptime.vonx.io/

**Comment by rajpalc7** [comment]
@WadeBarnes The changes are completed and tested in dev environment now

**Comment by WadeBarnes** [comment]
Looks good.

**Comment by rajpalc7** [comment]
@WadeBarnes The changes are completed and tested in dev environment now

**Comment by WadeBarnes** [comment]
Looks good.
