### ISSUE TITLE
BCGov Endorser Service for BCovrin Ledgers

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#61]
Create new (or repurpose existing) DIDs for use as Endorser DIDs on BCovrin ledgers. Setup Endorser services to use the DIDs, and register all issuers with the service. Turn existing endorsers into issuer (author) DIDs.

**Comment by WadeBarnes** [comment]
Endorser services for BCovrin `dev` and `test` have been provisioned.  Issuer registration yet to be done.

**Comment by WadeBarnes** [comment]
Endorser service for BCovrin `prod` has been provisioned. New DID dedicated to the endorser has been created.

Issuer registration for endorsers will be done as a separate task.
