### ISSUE TITLE
Setup Sysdig Dashboard 

### ISSUE THREAD

**Issue by rajpalc7** [bcgov/DITP-DevOps#63]
ca7f8f - Digital Trust Monitoring Services

**Comment by WadeBarnes** [comment]
PVC and Digital Trust Monitoring Services Audit - Prod dashboards need some updates as indicated on RC.

**Comment by rajpalc7** [comment]
Looks like Audit POD doesnt have any CPU and Memory assigned to it right now. Therefore there is no data available for those panel.

**Comment by WadeBarnes** [comment]
The Digital Trust Monitoring Services Audit Pod is configured exactly like the backup pods in other environments, therefore I would expect it would be able to display similar data in the charts and graphs.

Audit Pod Dashboard; https://app.sysdigcloud.com/#/shared/dashboard/bca447c4ba574b84b5fa250e6b1461ff?last=3600
Example Backup Container Dashboard; https://app.sysdigcloud.com/#/shared/dashboard/e15ce4fb75e34753b9a5853b1c5387f5?last=3600

**Comment by rajpalc7** [comment]
Digital Trust Monitoring Services-Audit  - A new page was created and data is visible now

**Comment by WadeBarnes** [comment]
Looks good.
