### ISSUE TITLE
Mediator Upgrades and Support/Monitoring

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#66]
- [x] Upgrade wallets to use Postgres 14
  - [x] `dev`
  - [x] `test`
  - [x] `prod`

- [x] Upgrade mediators to latest Aca-Py image
  - [x] `dev`
  - [x] `test`
  - [x] `prod`

- [x] Migrate mediators to use Askar wallets
  - [x] `dev`
  - [x] `test`
  - [x] `prod`

- [x] Support troubleshooting/performance monitoring

**Comment by WadeBarnes** [comment]
Upgrades and migrations completed in `prod` this morning.
