### ISSUE TITLE
Mediator Load testing

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#67]
Mediator load testing activities supporting/in parallel to #66

**Comment by swcurran** [comment]
Wade got the Askar Mediator running this morning and ran a pile of tests -- great results!  He only crashed the load generator -- AFAIK -- no fails.  @WadeBarnes can fill in the details but very positive results.

**Comment by WadeBarnes** [comment]
Example load test results can be found here; https://github.com/bcgov/DITP-DevOps/issues/68#issuecomment-1509093290

**Comment by esune** [comment]
@cvarjao @swcurran regarding the load testing exercise, @rajpalc7 indicates he has the load testing setup ready on his machine, but that is all we need for now. Would you be able to confirm whether additional testing activities are required (and what the expected outcome is)?

**Comment by swcurran** [comment]
@usingtechnology is working on a way to run the mediator with metrics collection (ELK Stack) active, so we can learn more about what is going on within the mediator.  @Jsyro is also working on a configuration to add Redis to the mediator, and we hope to be able to combine the efforts - do an apples to apples performance comparison to an instance with/without Redis.

**Comment by esune** [comment]
Thank you @swcurran. It sounds like @rajpalc7 can then stand on-hold if anything becomes necessary, but nothing specific is required from him at this time.
