### ISSUE TITLE
Deploy ACA-Py 0.8.1 to Mediator Dev, Test and Prod

### ISSUE THREAD

**Issue by swcurran** [bcgov/DITP-DevOps#68]
Please use the aries-mediator-service load testing tool to verify Dev before promoting to Test.  

Please use the aries-mediator-service load testing tool to verify Test, publish the results and request confirmation before promoting to Production.  Suggest that @cvarjao @swcurran @WadeBarnes and @esune be contacted for confirmation.

Progress:
- [x] `dev`
- [x] `test` - Load test results pending.
- [x] `prod`

**Comment by WadeBarnes** [comment]
`prod` was upgraded this morning.
