### ISSUE TITLE
Deploy new ledger browser to BCovrin ledgers

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#76]
See https://github.com/bcgov/von-network/issues/256. Updated ledger browser needs to be deployed at least for BCovrin Test.

**Comment by swcurran** [comment]
Thanks for this — it will be a big help!

**Comment by WadeBarnes** [comment]
The updated version of von-network has been deployed to all environments.  The issue with the malformed CRED_DEF record has been resolved; https://github.com/bcgov/von-network/issues/256#issuecomment-1567200116

**Comment by WadeBarnes** [comment]
I'm now looking into some errors reported in the image build logs to ensure they're not going to cause any issues.

**Comment by swcurran** [comment]
Awesome — thanks so much!!

**Comment by swcurran** [comment]
Hmm…looks like the filtering buries the app/browser though.  

If I search for a specific DID (say, WH45AYWZHX9SRbZgsGV2rG), it sits in “Loading” for a very long time and says no transactions found.
If I try to search for a certain page (like the last one), it sits in “Loading” for a very long time.

I think the almost 1M transactions is just too much for the browser…

Oh well.  I’ll avoid using it.  Hopefully, someone using the ledger (reading/writing) won’t be impacted by the ledger browser performance.

**Comment by WadeBarnes** [comment]
It will take a while before the transactions are fully loaded.  Try again later.

**Comment by swcurran** [comment]
Got it.  🤞

**Comment by WadeBarnes** [comment]
> I'm now looking into some errors reported in the image build logs to ensure they're not going to cause any issues.

It looks like the errors can be safely ignored.  Reinstalling the older version of `pip` during the build surfaces some false version compatibility/dependency issues.
