### ISSUE TITLE
Decommission existing Traction instances, set-up new production-ready instances

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#78]
Current Traction instances need to be decommissioned and a new DITP-maintained and production-ready set of DEV/TEST/PROD instances deployed.

Acceptance Criteria:
- [ ] ~~Backup wallets and decommission old EMDT instances in namespace set `bc0192-*`~~
- [ ] ~~Decommission Anoncreds Workshop instance (if still up) in namespace `a99fd4-test`~~
- [x] Deploy `DEV` instance in `bc0192-dev`. Instance should be automatically updated when PRs are merged into `main`
- [x] Deploy `TEST` instance in `bc0192-test`. Instances should be updated on-demand, targeting the latest available release/chart.
- [ ] ~~Deploy `PROD` instance in `bc0192-prod`. Instances should be updated on-demand, targeting the latest available release/chart.~~
- [x] Decommission sandbox DITP instance in namespace `e79518-dev`

Use a separate repository to store the deployment-specific configurations. The main Traction repo should - as much as possible - be used only for product changes and settings that are not use-case specific. Remove existing references from main `traction` repo.

*Note:* the BC Wallet showcase is using the DTS sandbox instance - coordinate with the the decommissioning so that they can request new tenants in the new instances.

**Comment by esune** [comment]
@krobinsonca just confirming, one last time, that the Traction instances in the `bc0192-*` namespaces can be safely decommissioned. Is there anything we should keep (i.e.: wallet backups)?

**Comment by krobinsonca** [comment]
Correct, they can be decommissioned. No backups are needed.

**Comment by swcurran** [comment]
How soon is this happening. We said that the Workshop instance would stay around for at least a week or so.

**Comment by esune** [comment]
> How soon is this happening? We said that the Workshop instance would stay around for at least a week or so.

This is not slated to happen for ate least the next couple of weeks - looking to further improve the Helm charts and CI/CD before then.

**Comment by esune** [comment]
@cvarjao @wadeking98 the new instances of Traction are up and running. @i5okie will add details (URLs) to request new tenants to this ticket (dev/test/prod): once migrated to the new instances please give us a heads up so we can decommission the current DTS deployment.

@swcurran we are also finally going to remove the Anoncreds workshop instance: any objections?

**Comment by i5okie** [comment]
The following instances have been deployed and are ready to be used:

`dev`:
https://tenant-ui-dev.apps.silver.devops.gov.bc.ca/
https://traction-acapy-dev.apps.silver.devops.gov.bc.ca/
https://traction-acapy-admin-dev.apps.silver.devops.gov.bc.ca/api/doc

`test`:
https://tenant-ui-test.apps.silver.devops.gov.bc.ca/
https://traction-acapy-test.apps.silver.devops.gov.bc.ca/
https://traction-acapy-admin-test.apps.silver.devops.gov.bc.ca/api/doc

`prod`:
https://tenant-ui-prod.apps.silver.devops.gov.bc.ca/
https://traction-acapy-prod.apps.silver.devops.gov.bc.ca/
https://traction-acapy-admin-prod.apps.silver.devops.gov.bc.ca/api/doc

**Comment by cvarjao** [comment]
@esune, which ledger each instance is pointing at? I am assuming multi r/w ledger is not yet supported, right?

**Comment by esune** [comment]
> @esune, which ledger each instance is pointing at? I am assuming multi r/w ledger is not yet supported, right?

Correct, this is a work in progress. Currently they use BCovrin Test for both read and write. This will change in the future as we implement the multi-ledger features, as well as the changes to the endorser service that are required to auto-approve new authors from known multi-tenant deployments (such as out Traction instances).

**Comment by i5okie** [comment]
Production instance has been uninstalled for the time being.

**Comment by i5okie** [comment]
Production instance has been uninstalled for the time being.

**Comment by i5okie** [comment]
Traction DTS has been uninstalled.
