### ISSUE TITLE
ELK Stack for log shipping/monitoring

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#80]
An ELK stack is required to monitor and ship logs for our services (in particular Traction tenants, see https://github.com/bcgov/traction/issues/545). We should determine whether we can re-use the platform's deployment or, more likely, need to stand-up our own.

Acceptance Criteria:
- Determine possibility of customizing access to each tenant
- Determine possibility to consume logfile sources different than stdout
- ELK stack accessible for our project(s), either self-hosted or platform-hosted

**Comment by esune** [comment]
Useful resources (thanks @loneil ): https://github.com/bcgov/elmsd-nodejs/tree/main/packages/openshift/templates/efk-stack

**Comment by WadeBarnes** [comment]
Closing in favor of https://github.com/bcgov/DITP-DevOps/issues/117
