### ISSUE TITLE
Register Sovrin TestNet issuers with Sovrin TestNet instance of the BC Endorser service

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#85]
Sovrin TestNet instance of the BC Endorser service:
- [aries-endorser-agent-sovrin](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/4a9599-test/deploymentconfigs/aries-endorser-agent-sovrin)

Register the following issuers with the Sovrin TestNet instance of the BC Endorser service:
- [ ] [email-verification-agent](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a99fd4-dev/deploymentconfigs/email-verification-agent) - dev instance
- [ ] [email-verification-agent](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a99fd4-test/deploymentconfigs/email-verification-agent) - test instance
- [ ] [email-verification-agent](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a99fd4-prod/deploymentconfigs/email-verification-agent) - prod instance
- [ ] [agent-openvp](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a99fd4-dev/deploymentconfigs/agent-openvp) - dev instance
- [ ] [agent-openvp](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a99fd4-test/deploymentconfigs/agent-openvp) - test instance
- [ ] [agent-openvp](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a99fd4-prod/deploymentconfigs/agent-openvp) - prod instance
- [ ] [agent-a2a](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a99fd4-dev/deploymentconfigs/agent-a2a) - dev instance
- [ ] [agent-a2a](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a99fd4-test/deploymentconfigs/agent-a2a) - test instance
- [x] [agent-lsbc](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e79518-dev/deploymentconfigs/agent-lsbc) - dev instance
- [x] [agent-lsbc](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e79518-test/deploymentconfigs/agent-lsbc) - test instance

Cleanup
- [ ] Ensure the agents are demoted to the role of author once they have been registered with the endorser service.

_Note: - Some agents may need to be upgraded to an ACA-Py version that supports the endorser protocols before they can be connected to the endorser service._  Refer to https://github.com/bcgov/DITP-DevOps/issues/18 for details.

Scripts to perform the agent registration can be found here; [registerAuthor](https://github.com/bcgov/dts-endorser-service/blob/main/openshift/manage#L47-L62).

**Comment by WadeBarnes** [comment]
Blocked by https://github.com/bcgov/DITP-DevOps/issues/28

**Comment by esune** [comment]
Closing as all remaining agents that would require registering have been decommisioned.
