### ISSUE TITLE
Register Sovrin MainNet issuers with Sovrin MainNet instance of the BC Endorser service

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#86]
Sovrin MainNet instance of the BC Endorser service:
- [aries-endorser-agent-sovrin](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/4a9599-prod/deploymentconfigs/aries-endorser-agent-sovrin)

Register the following issuers with the Sovrin MainNet instance of the BC Endorser service:
- [ ] [agent-primary](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/7cba16-prod/deploymentconfigs/agent-primary) - BC Registries Issuer Agent
- [ ] [mines-permitting-agent-primary](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a3e512-prod/deploymentconfigs/mines-permitting-agent-primary)
- [ ] [ghg-emissions-agent-primary](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/a3e512-prod/deploymentconfigs/ghg-emissions-agent-primary)
- [x] [agent-lsbc](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e79518-prod/deploymentconfigs/agent-lsbc)
- [ ] [agent-lcrb](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e79518-prod/deploymentconfigs/agent-lcrb)
- [ ] [agent-buybc](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e79518-prod/deploymentconfigs/agent-buybc)

Cleanup
- [ ] Ensure the agents are demoted to the role of author once they have been registered with the endorser service.

_Note: - Some agents may need to be upgraded to an ACA-Py version that supports the endorser protocols before they can be connected to the endorser service._  Refer to https://github.com/bcgov/DITP-DevOps/issues/18 for details.

Scripts to perform the agent registration can be found here; [registerAuthor](https://github.com/bcgov/dts-endorser-service/blob/main/openshift/manage#L47-L62).

**Comment by WadeBarnes** [comment]
Blocked by https://github.com/bcgov/DITP-DevOps/issues/28

**Comment by WadeBarnes** [comment]
LSBC Agent has been connected to the endorser service and the agent's DID has been demoted to author; https://indyscan.io/tx/SOVRIN_MAINNET/domain/157681

**Comment by esune** [comment]
@WadeBarnes Can we close this issue, since we are planning to migrate the agents?

**Comment by WadeBarnes** [comment]
Yes
