### ISSUE TITLE
Register BCovrin Test issuers with the BCovrin Test instance of the BC Endorser service

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/DITP-DevOps#88]
BCovrin Test instance of the BC Endorser service:
- [aries-endorser-agent-bcovrin](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/4a9599-test/deploymentconfigs/aries-endorser-agent-bcovrin)

Register the following issuers with the BCovrin Test instance of the BC Endorser service:
- [ ] [agent-primary](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/7cba16-test/deploymentconfigs/agent-primary) - BC Registries Issuer Agent
- [ ] Traction instances - ToDo - List them
- [ ] [agent-bcreg](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e79518-dev/deploymentconfigs/agent-bcreg)
- [ ] [agent-lcrb](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e79518-test/deploymentconfigs/agent-lcrb)
- [ ] [agent-buybc](https://console.apps.silver.devops.gov.bc.ca/k8s/ns/e79518-test/deploymentconfigs/agent-buybc)

Cleanup
- [ ] Ensure the agents are demoted to the role of author once they have been registered with the endorser service.

_Note: - Some agents may need to be upgraded to an ACA-Py version that supports the endorser protocols before they can be connected to the endorser service._  Refer to https://github.com/bcgov/DITP-DevOps/issues/18 for details.'

Scripts to perform the agent registration can be found here; [registerAuthor](https://github.com/bcgov/dts-endorser-service/blob/main/openshift/manage#L47-L62).

**Comment by esune** [comment]
@WadeBarnes Can we close this issue, since we are planning to migrate the agents?

**Comment by WadeBarnes** [comment]
Yes
