### ISSUE TITLE
Smoke Test the ACA-Py 0.9.0-rc0 release so we can get the final release out

### ISSUE THREAD

**Issue by swcurran** [bcgov/DITP-DevOps#90]
@WadeBarnes or someone — could you smoke test the ACA-Py 0.9.0-rc0 release so that we can be confident in putting out the final 0.9.0 release?

Perhaps document what you do in smoke testing so that others can do it in the future.

Please reassign if this should go to someone else.

**Comment by swcurran** [comment]
Per RocketChat message — we can’t use aries-cloudagent-container as the source of the smoke test, since that is stuck at Python 3.6 — we’ll need to get it updated to use Python 3.9. Adding ticket to update aries-cloudagent-container’s dockerfile.

**Comment by WadeBarnes** [comment]
I'll use the `ghcr.io/hyperledger/aries-cloudagent-python:py3.9` `0.9.0-rc0` image(s) for the smoke test.

**Comment by WadeBarnes** [comment]
I've smoke tested `ghcr.io/hyperledger/aries-cloudagent-python:py3.9-indy-1.16.0-0.9.0-rc0`.
Process:
- Upgrade our A2A Issuer Agent (issues developer level Lawyer credentials for testing) from `py3.9-indy-1.16.0-0.8.2` to `:py3.9-indy-1.16.0-0.9.0-rc0`
- Remove previous credentials from the BC Wallet.
- Issue new A2A Issuer, and Open VP credentials.
- Use the new credentials to authenticate with the ACM (Access to Court Materials) website.
- Log out
- Revoke the new A2A Issuer credential.
- Try to authenticate with ACM, to ensure the credential was revoked and the authentication fails.

**Comment by swcurran** [comment]
Nice!  Thanks.

**Comment by WadeBarnes** [comment]
The A2A Issuer Agent is using `indy` storage, so I'm looking for a candidate service that's using `askar` storage to complete the testing.

**Comment by swcurran** [comment]
@loneil is looking at updating a Traction instance that he previously updated using the 0.8.3pre pseudo tagged image.

**Comment by WadeBarnes** [comment]
> @loneil is looking at updating a Traction instance that he previously updated using the 0.8.3pre pseudo tagged image.

Great, that will cover the `askar` storage side.  I'll leave it with @loneil.

**Comment by loneil** [comment]
For trying with Traction: https://github.com/bcgov/traction/pull/729

**Comment by swcurran** [comment]
Completed.
