### ISSUE TITLE
Add SysDig monitoring to Traction namespaces

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#92]
Add SysDig monitoring to `bc0192` namespace set. Follow what already done for this ticket as draft: https://github.com/bcgov/DITP-DevOps/issues/63

Acceptance Criteria:
- Add SysDig dashboards to `bc0192-dev`, `bc0192-test`, `bc0192-prod`
- Add alerts for appropriate event in those environments
- Provide DTS DevOps members with access to the dashboards

**Comment by rajpalc7** [comment]
Hi @esune - Can you please let me know the who will require access to bc0192 namespace ?

**Comment by rajpalc7** [comment]
Assuming Acceptance Criteria is to add dashboard monitoring in dev , test and prod environment and also adding alerts for them

**Comment by WadeBarnes** [comment]
@rajpalc7, I don't see a `sysdigteam` file for `bc0192` here; https://github.com/bcgov/DITP-DevOps/tree/main/sysdig.  No PRs for one either.

**Comment by WadeBarnes** [comment]
@rajpalc7, Where would I find the links to the dashboards?  I don't see them listed here with the rest of them; https://trello.com/c/Mj9EqIzq/88-sysdig-dashboards

**Comment by WadeBarnes** [comment]
@rajpalc7, Were you going to do backups for the dashboards you created for `bc0192`?  I don't see a PR for them or any here; https://github.com/bcgov/DITP-DevOps/tree/main/sysdig/dashboard%20backups

**Comment by WadeBarnes** [comment]
@rajpalc7, Can you provide a summary and links to the dashboards and alerts so I'm not having to search for and guess at what you did?  Thanks.

**Comment by rajpalc7** [comment]
@WadeBarnes - I just followed the ticket's acceptance criteria and did what was asked to do there. I can create the links for dashboards and alerts shortly.

**Comment by rajpalc7** [comment]
Links for dashboards and alerts are available on https://trello.com/c/Mj9EqIzq/88-sysdig-dashboards now

**Comment by rajpalc7** [comment]
https://github.com/bcgov/DITP-DevOps/pull/105/commits - Dashboards backup and sysdig team PR

**Comment by WadeBarnes** [comment]
@rajpalc7, All of the alerts for the `bc0192-team` are looking at the wrong namespace, they all contain `a99fd4` in their queries.  Please review and fix.

**Comment by WadeBarnes** [comment]
Dashboards:
- Traction - backup-int-traction-Test - bc0192
  - No data being displayed
- Traction - backup-int-wallets-Test - bc0192
  - No data being displayed
- Traction - tenant-ui-Dev - bc0192
  - Missing lots of data
- Traction - tenant-ui-Test- bc0192
  - LInk to PVC Dashboard goes to https://app.sysdigcloud.com/#/shared/dashboard/a09b8b779e584909881eca7127eae0a3?last=3600 which is not a PVC dashboard.
- Traction - traction-acapy- Dev - bc0192
  - Similar issue with the link to the PVC dashboard
- Traction - traction-acapy- Prod- bc0192
  - Similar issue with the link to the PVC dashboard
- Traction - traction-acapy- Test - bc0192
  - Similar issue with the link to the PVC dashboard
- Traction - traction-tenant-proxy-Dev - bc0192
  - Similar issue with the link to the PVC dashboard
- Traction - traction-tenant-proxy-Prod - bc0192
  - Similar issue with the link to the PVC dashboard
- Traction - traction-tenant-proxy-Test - bc0192
  -  Similar issue with the link to the PVC dashboard
- Traction -postgresql-Dev - bc0192
  -  Similar issue with the link to the PVC dashboard
- Traction -postgresql-Prod - bc0192
  -  Similar issue with the link to the PVC dashboard
- Traction -postgresql-Test - bc0192
  -  Similar issue with the link to the PVC dashboard

**Comment by rajpalc7** [comment]
Hi @WadeBarnes - We are seeing this issues because looks like they have made changes in the pod names. I think it will be better for me to work on these dashboards once we have something permanent. 
What do you suggest ?

**Comment by esune** [comment]
> Hi @WadeBarnes - We are seeing this issues because looks like they have made changes in the pod names. I think it will be better for me to work on these dashboards once we have something permanent. What do you suggest ?

What do you mean by changes in the pod names, exactly? Is this about the Tenant UI pods clightly changing the naming pattern, or something else? Can you use k8s labels as selectors, which will likely be more consistent, instead of pod names?

**Comment by rajpalc7** [comment]
I mean deployment label names but i did talk to Lucas about it and he says it will remain the same from now on. Hopefully!

**Comment by rajpalc7** [comment]
@WadeBarnes - I have made all the necessary changes according to the new deployment label and PVC dashboards now. Ready for review

**Comment by WadeBarnes** [comment]
Alerts seem to be working now- thanks.

The dashboards are all showing data now and the links to the PVC Dashboard are working - thanks.

The PVC Dashboard needs a few updates though:
- It has a link to itself - please remove the **Links** section.
- PVC metric display panels are labeled as Backup PVC.  There are no Backup PVCs defined it the Traction namespaces, yet.  I assume these are actually for the Traction database.  Please update the labels appropriately.

![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/2b13a081-698f-41d1-99b0-06562eead308)

**Comment by rajpalc7** [comment]
Thanks @WadeBarnes PVC dashboard is fixed now. Ready for review

**Comment by WadeBarnes** [comment]
Looks good.  Thanks
