### ISSUE TITLE
Upgrade VC-AuthN to 2.0

### ISSUE THREAD

**Issue by esune** [bcgov/DITP-DevOps#93]
Upgrade the existing deployments of VC-AuthN in OCP namespace set `e79518`.

There are currently two sets of deployments for VC-AuthN:
- A "standard" `vc-authn` deployment
- A "revocation" `vc-authn` deployment (with the `-rev` suffix)

They will both be replaced by the new 2.0 instance.

**Upgrade Path**

1. Deploy VC-AuthN 2.0 in the `e79518-dev` namespace
2. Transfer proof-configurations, client configurations and mappers from old instances to the new one (only Keycloak, old standalone app settings are not required)
3. Update `dev` realm settings to use the new VC-AuthN instance as IdP
3. Spin down the existing instances
4. Test application
5. Repeat for `test`, `prod`

**Comment by esune** [comment]
Realms where the VC-AuthN IdP configuration will need to be updated:
- https://dev.loginproxy.gov.bc.ca/auth/admin/digitaltrust-citz/console
- https://test.loginproxy.gov.bc.ca/auth/admin/digitaltrust-citz/console
- https://loginproxy.gov.bc.ca/auth/admin/digitaltrust-citz/console
- https://dev.loginproxy.gov.bc.ca/auth/admin/access-to-court-materials-jag/console/#/realms/access-to-court-materials-jag
- https://test.loginproxy.gov.bc.ca/auth/admin/access-to-court-materials-jag/console/#/realms/access-to-court-materials-jag
- https://dloginproxy.gov.bc.ca/auth/admin/access-to-court-materials-jag/console/#/realms/access-to-court-materials-jag

**Comment by i5okie** [comment]
`vc-authn-oidc` (v2,0) has been deployed to `e79518-dev`, `e79518-test`, `e79518-prod`;
Configuration of `digitaltrust-citz` clients has been completed.

Waiting to verify the identity provider mappers prior to updating the `access-to-court-materials-jag` realms and coordinating with the ACM developers the app updates.

**Comment by esune** [comment]
Closing this issue: the initial upgrade work was completed successfully and #118 is now tracking the last batch of changes.
