### ISSUE TITLE
The scripts for the uptime notification are not working as expected

### ISSUE THREAD

**Issue by rajpalc7** [bcgov/DITP-DevOps#94]
The scripts for the uptime notification are not working as expected, They don't seem to support days and exact time . If any service is down for more than a day, it will just show as the service was just down for some hours.

Please look into fixing the scripting part of the uptime notification and make sure it shows that service was down for days, time and hours.

**Comment by rajpalc7** [comment]
This ticket is completed now, moved to review/qa on 23rd August

**Comment by WadeBarnes** [comment]
Waiting for @rajpalc7 to create a PR containing the rocket.chat integration script updates and link it to this issue.

**Comment by rajpalc7** [comment]
https://github.com/bcgov/platform-services-sre/pull/20 - A new PR has been created

**Comment by WadeBarnes** [comment]
@rajpalc7, please she Shell and my comments on the PR.

**Comment by rajpalc7** [comment]
Hi Wade, I thought shelly's comments were addressed when I was showing the demo yesterday.

**Comment by WadeBarnes** [comment]
If you look at the diff here; https://github.com/bcgov/platform-services-sre/pull/20/files

You'll see there are still some outstanding whitespace issues to address:
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/65f1497c-e926-4c4c-b51b-d3aa08b6f2a0)

Such as extra spaces here:
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/7491cfdf-b473-4d49-911a-6b2e97405b18)

Missing spaces here:
![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/8c488b2b-a8f3-476d-bb81-a32a7d332f5f)

and, seemingly a combination of extra/missing spaces or tabs here:

![image](https://github.com/bcgov/DITP-DevOps/assets/10504350/e0e87117-2fed-4a52-bc2d-fa84e28971b8)

**Comment by rajpalc7** [comment]
Fixed the formatting now

**Comment by rajpalc7** [comment]
https://github.com/bcgov/platform-services-sre/compare/main...rajpalc7:platform-services-sre:main - this should do it

**Comment by WadeBarnes** [comment]
Complete
