### ISSUE TITLE
Add uptime monitoring for the BC Wallet Showcase

### ISSUE THREAD

**Issue by rajpalc7** [bcgov/DITP-DevOps#95]
Add uptime monitoring for the BC Wallet Showcase in the dev, test, and prod environments.

URL endpoints to be monitored can be found here:

**Dev:**

Frontend:
https://bc-wallet-demo-dev.apps.silver.devops.gov.bc.ca/digital-trust/showcase/

Backend:
https://bc-wallet-demo-dev.apps.silver.devops.gov.bc.ca/digital-trust/showcase/server/ready

Agent:
https://bc-wallet-demo-dev.apps.silver.devops.gov.bc.ca/digital-trust/showcase/agent/ready

**Test:**

Frontend:

https://bc-wallet-demo-test.apps.silver.devops.gov.bc.ca/digital-trust/showcase/
Backend:

https://bc-wallet-demo-test.apps.silver.devops.gov.bc.ca/digital-trust/showcase/server/ready
Agent:

https://bc-wallet-demo-test.apps.silver.devops.gov.bc.ca/digital-trust/showcase/agent/ready

**Prod:**

Frontend:
https://bc-wallet-demo.apps.silver.devops.gov.bc.ca/digital-trust/showcase/

Backend:
https://bc-wallet-demo.apps.silver.devops.gov.bc.ca/digital-trust/showcase/server/ready

Agent:
https://bc-wallet-demo.apps.silver.devops.gov.bc.ca/digital-trust/showcase/agent/ready

**Comment by WadeBarnes** [comment]
Reviewed.  Looks good.
